
-- Kalimdor
 [_] "Ashenvale"
 [_] "Azshara"
 [X] "Azuremyst Isle"
 [X] "Bloodmyst Isle"
 [X] "Darkshore"
 [X] "Darnassus"
 [_] "Desolace"
 [_] "Durotar"
 [_] "Dustwallow Marsh"
 [X] "Felwood"
 [_] "Feralas"
 [_] "Molten Front"
 [X] "Moonglade"
 [X] "Mount Hyjal"
 [_] "Mulgore"
 [_] "Northern Barrens"
 [X] "Orgrimmar"
 [_] "Silithus"
 [_] "Southern Barrens"
 [_] "Stonetalon Mountains"
 [_] "Tanaris"
 [X] "Teldrassil"
 [X] "The Exodar"
 [_] "Thousand Needles"
 [X] "Thunder Bluff"
 [_] "Uldum"
 [_] "Un'Goro Crater"
 [_] "Winterspring"
	
-- Eastern Kingdoms
 [_] "Abyssal Depths"
 [_] "Arathi Highlands"
 [_] "Badlands"
 [_] "Blasted Lands"
 [_] "Burning Steppes"
 [_] "Deadwind Pass"
 [X] "Dun Morogh"
 [_] "Duskwood"
 [_] "Eastern Plaguelands"
 [X] "Elwynn Forest"
 [X] "Eversong Woods"
 [_] "Ghostlands"
 [_] "Gilneas"
 [_] "Gilneas City"
 [_] "Hillsbrad Foothills"
 [X] "Ironforge"
 [_] "Isle of Quel'Danas"
 [_] "Kelp'thar Forest"
 [_] "Loch Modan"
 [_] "Northern Stranglethorn"
 [_] "Redridge Mountains"
 [_] "Ruins of Gilneas"
 [_] "Ruins of Gilneas City"
 [_] "Searing Gorge"
 [_] "Shimmering Expanse"
 [X] "Silvermoon City"
 [_] "Silverpine Forest"
 [X] "Stormwind City"
 [_] "Swamp of Sorrows"
 [_] "The Cape of Stranglethorn"
 [_] "The Hinterlands"
 [_] "The Scarlet Enclave"
 [_] "Tirisfal Glades"
 [_] "Tol Barad"
 [_] "Tol Barad Peninsula"
 [_] "Twilight Highlands"
 [X] "Undercity"
 [_] "Vashj'ir"
 [_] "Western Plaguelands"
 [X] "Westfall"
 [_] "Wetlands"
	
-- Outland
 [_] "Blade's Edge Mountains"
 [_] "Hellfire Peninsula"
 [_] "Nagrand"
 [_] "Netherstorm"
 [_] "Shadowmoon Valley"
 [_] "Shattrath City"
 [_] "Terokkar Forest"
 [_] "Zangarmarsh"
	
-- Northrend
 [_] "Borean Tundra"
 [_] "Crystalsong Forest"
 [_] "Dragonblight"
 [_] "Grizzly Hills"
 [_] "Howling Fjord"
 [_] "Hrothgar's Landing"
 [_] "Icecrown"
 [_] "Sholazar Basin"
 [_] "The Storm Peaks"
 [_] "Wintergrasp"
 [_] "Zul'Drak"
	
-- Pandaria
 [_] "Dread Wastes"
 [_] "Isle of Giants"
 [_] "Isle of Thunder"
 [_] "Krasarang Wilds"
 [_] "Kun-Lai Summit"
 [_] "Shrine of Seven Stars"
 [_] "Shrine of Two Moons"
 [_] "The Jade Forest"
 [_] "The Veiled Stair"
 [_] "The Wandering Isle"
 [_] "Timeless Isle"
 [_] "Townlong Steppes"
 [_] "Vale of Eternal Blossoms"
 [_] "Valley of the Four Winds"
	
-- Draenor
 [_] "Ashran"
 [_] "Frostfire Ridge"
 [_] "Gorgrond"
 [_] "Nagrand"
 [_] "Shadowmoon Valley"
 [_] "Spires of Arak"
 [_] "Stormshield"
 [_] "Talador"
 [_] "Tanaan Jungle"
