--
-- Azuremyst Isle
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Exodar"					,["x"] = 37.00	,["y"] = 47.00	,["lore"] = "<HTML><BODY><P>The Exodar is the enchanted capital city of the draenei who chose to depart from Draenor.<BR/><BR/>At some point before the present, the naaru arrived in the realm of Outland with a \"dimensional fortress\" known as Tempest Keep.<BR/>The naaru dispersed throughout the ravaged world, leaving the fortress defenseless.<BR/>Seeing an opportunity to strike, Kael'thas Sunstrider and his many blood elf legions assaulted Tempest Keep and captured it, taking possession of its treasures and kidnapping the sole naaru occupant, M'uru, sending him back to Silvermoon City for the magisters to utilize in their thirst for magic.<BR/><BR/>Velen, the courageous prophet who had led the draenei people since their exodus from Argus millennia before, had hid with the remainder of his people in the wake of the Legion-instigated orcish onslaught.<BR/>With the Broken Farseer Nobundo, first of the draenei shaman, at his side, the Prophet personally led a raid on Tempest Keep to wrest control of one of its satellite structures, the Exodar.<BR/><BR/>The draenei eventually took control of the Exodar and used it to escape Outland.<BR/>The blood elves, discovering what the draenei were planning, sabotaged the dimensional engines of the vessel.<BR/>When the draenei activated it, the engine malfunctioned and sent the Exodar hurtling out of control through the Twisting Nether until it reached the closest habitable planet, Azeroth.<BR/>The crippled ship screamed across the skies of Northern Kalimdor, crystals flying everywhere, until it crash-landed on a small island chain off the coast of Darkshore.<BR/>The survivors took the islands as their new homeland, and set up their new capital in the largest intact portion of the still-smoking ship.</P><BR/><IMG align=\"CENTER\" src=\"Interface/AddOns/LoreLibrary/Images/crest_Draenei\" /><BR/><BR/><BR/><BR/><BR/><P align=\"CENTER\"><BR/>Draenei Crest</P><BR/></BODY></HTML>"}
{["title"] = "Silvermyst Isle"			,["x"] = 13.40	,["y"] = 89.80	,["lore"] = "Silvermyst Isle used to contain a small Night Elf fishing vilage.\nThe crashing of the Exodar dropped crystalline shards on the island that drove the moonkin mad, causing them to rampage over the village, killing most of the inhabitants."}
{["title"] = "Wrathscale Point"			,["x"] = 29.61	,["y"] = 79.20	,["scale"] = 3	,["lore"] = ""}
{["title"] = "Odesyus' Landing"			,["x"] = 46.73	,["y"] = 70.30	,["lore"] = "Odesyus' Landing is a small outpost founded by an Alliance fleet led by Admiral Odesyus.\nAdmiral Odesyus was forced to port on Azuremyst Isle after the fleets Nautical Compass and Nautical Map were stolen by the Venture Co."}
{["title"] = "Azure Watch"				,["x"] = 49.16	,["y"] = 51.00	,["lore"] = "Azure Watch is a forward outpost of the Hand of Argus.\nThe Hand of Argus is an organization of draenei paladins and vindicators that serve as the primary military and police force of the Exodar."}
{["title"] = "Stillpine Hold"			,["x"] = 45.36	,["y"] = 20.63	,["lore"] = "Stillpine Hold is a small settlement and the home to the Furbolg Stillpine tribe.\nThe hold within the cave itself is occupied by corrupted and thus hostile moonkin, which the furbolgs wish to get rid of."}
{["title"] = "Menagerie Wreckage"		,["x"] = 54.98	,["y"] = 21.29	,["lore"] = "The Menagerie Wreckage is a part of the Exodar that contained captured animals from Draenor.\nThe caged creatures tumbled from the Exodar before it plowed into Wildwind Peak on the western part of the Azuremyst Isle, and now threaten the local fauna with their alien presence."}
