--
-- Bloodmyst Isle
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Blood Watch"			,["x"] = 54.89	,["y"] = 56.35	,["scale"] = 2	,["lore"] = "Blood Watch is a forward outpost of the Hand of Argus, and main draenei settlement on Bloodmyst Isle.\nIt is in fact many big crystal pieces of the Exodar that have been converted into their base of operations on the island."}
{["title"] = "Wrathscale Lair"		,["x"] = 68.84	,["y"] = 68.04	,["scale"] = 2	,["lore"] = ""}
{["title"] = "Wyrmscar Island"		,["x"] = 72.84	,["y"] = 20.86	,["scale"] = 2	,["lore"] = "Wyrmscar Island is now home to bones, the restless spirits of slain green whelplings, and the ghost of Prince Toreth, a night elf prince of Loreth'Aran.\nRazormaw was a lieutenant of Deathwing who lead the destruction of Loreth'Aran, resulting in the death of both Night Elf and Green Dragons.  \nHis hatred is so great he remains on the island even in death."}
{["title"] = "Bloodcurse Isle"		,["x"] = 85.64	,["y"] = 53.60	,["scale"] = 2	,["lore"] = "Not much is known about the Bloodcurse Naga.\nAt the highest point of the isle is a Statue of Queen Azshara, first the beloved ruler of the Night Elves before becomming the Queen of the Naga."}
{["title"] = "Ruins of Loreth'Aran"	,["x"] = 61.29	,["y"] = 48.52	,["scale"] = 2	,["lore"] = "The night elves who once inhabited this city were blessed by the Green dragonflight and its queen Ysera, and the Dragon Riders of Loreth'Aran rode these powerful green dragons into battle while also living alongside them.\nThe city was destroyed when the black dragonflight betrayed their green kin and descended upon the unwary night elves and green dragons.\nLed by a lieutenant of Deathwing, the fearsome Razormaw, the black dragonflight wiped out Loreth'Aran and its defenders in a savage maelstrom of flame and death.\n\nThe city of Loreth'Aran's destruction was made complete by the cataclysm, as the ocean swept in and the earth erupted, leaving only a few remaining ruins scattered across separate islands where once a shining city stood"}
{["title"] = "Warp Piston"			,["x"] = 53.37	,["y"] = 19.56	,["lore"] = "The Warp Piston is presumably a piece of the Exodar allowing it to travel, that broke off during its crash landing."}
{["title"] = "Axxarien"				,["x"] = 40.73	,["y"] = 34.16	,["scale"] = 2	,["lore"] = "Axxarien is a Satyr outpost led by their leader, Zevrax.\nThe sect is trying to use the crystalline shards from the Exodar's crash, which corrupted the area, as weapons."}
{["title"] = "Vector Coil"			,["x"] = 14.72	,["y"] = 53.57	,["scale"] = 2	,["lore"] = "The Vector Coil is a power core portion of the Exodar that crashed into western Bloodmyst Isle.\nThe area is a source of power of the Blood elf invaders in the Azuremyst Isles, and is fortified by saboteurs and agents of the Sunhawks, minions of Kael'thas Sunstrider.\nThe blood elves are pumping magic power out of the crystals to empower their own.\nAn eredar named Sironas is the leader of the Sunhawks in Bloodmyst and is harvesting power from the Vector Coil itself.\n\nThe sun gate is located to the south of the Vector Coil and it is guarded by Sunhawk Defenders and Sunhawk Pyromancers.\nIt is used to summon more and more Blood Elf invaders into the island from Outland.\nThe Vector Coil and the Sun Gate are both tainted due to the blood crystals from the Exodar's crash landing."}
{["title"] = "Nazzivian"			,["x"] = 39.34	,["y"] = 78.70	,["scale"] = 3	,["lore"] = "Nazzivian is an extensive Nazzivus satyr encampment located in southwestern Bloodmyst Isle.\nThe Nazzivian satyr appear to have a connection to a Felgaurd named Tzerak."}
