--
-- Dun Morogh
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "New Tinkertown"		,["x"] = 49.53	,["y"] = 45.43	,["scale"] = 0.5	,["lore"] = "<HTML><BODY><P>Following the conclusion of Operation: Gnomeregan, High Tinker Mekkatorque and his people have gained a foothold just outside the city in New Tinkertown.<BR/><BR/>Resolute in reclaiming their lost capital, Gnomeregan's exiles have begun an assault against the traitorous Mekgineer Thermaplugg.<BR/>Traveling from their temporary residence in Ironforge, they are led by the esteemed High Tinker Gelbin Mekkatorque, leader of the gnomes, and seek to restore Gnomeregan to its past glory.</P><BR/><IMG align=\"CENTER\" src=\"Interface/AddOns/LoreLibrary/Images/crest_Gnome\" /><BR/><BR/><BR/><BR/><BR/><P align=\"CENTER\"><BR/>Gnome Crest</P><BR/></BODY></HTML>"}
{["title"] = "Kharanos"				,["x"] = 53.49	,["y"] = 51.13	,["lore"] = "Kharanos is a bustling little town nestled among the mountain peaks of Dun Morogh. The town is surrounded by the stark wintry wilds of Dun Morogh, so adventure is a common commodity.\nKharanos is home to a large forge, a gnomish workshop, and the famous Thunderbrew Distillery, where adventurers can sit down and drink some of the best ale available in the world.\n\nFor all its quaint charm, Kharanos is a hub of military activity, defending against all manner of threats in the region.\nDirectly to the west is a large cavern inhabited by fierce Wendigo.\nTo the northwest, the Frostmane trolls have entrenched themselves at Shimmer Ridge.\n\nOnce, a giant frostame troll attacked the town and almost every dwarf.\nOnly Lazlo Grindwidget was able to defeat the troll thus he was honored as a hero of Kharanos.\n\nDuring one of the earthquakes preceding the Shattering, the Distillery was damaged and High Priest Rohan, Anduin Wrynn, and Aerin worked hard to help the injured and free the trapped.\nAfter clearing out the first floor an aftershock hit Kharanos, causing the remains of building to fall into a sinkhole.\nAerin, Anduin's friend and protector, was in the building when it fell into the earth and died with the others that were still inside.\nAnduin used all his strength to try to save her from underneath the rubble, his fingers were bloody and his strength diminished, crying for surrounding dwarves and draenei to help him, until he passed out from exhaustion.\nAfter the shattering, the Brewery ws rebuild."}
{["title"] = "Ironforge"			,["x"] = 60.38	,["y"] = 33.41	,["scale"] = 0.5	,["lore"] = "<HTML><BODY><P>Ironforge is the capital city of the dwarves, a member of the Alliance.<BR/>It is the ancestral home of the Bronzebeard dwarves.<BR/>The Council of Three Hammers rules the kingdom of Khaz Modan from the throne room within the city.<BR/><BR/>Carved into the stone heart of Khaz Modan, the mighty city of Ironforge is a testament to the dwarves’ strength and resilience.<BR/>The city is perhaps the most intricate of the Alliance cities, boasting many small passageways, shops built into the rock walls, and cavernous rooms.<BR/>The feel of the city is a bustling, rowdy, and somewhat industrial one.<BR/>However, it is predominantly safe-feeling and cozy; fires roar in the hearths of the inns and shops, and much dwarven laughing and frivolity is to be heard.<BR/>Also, unlike Stormwind and Darnassus, the city is actually a massive cavern carved into the earth by the dwarves; the ceiling and floor are both hard stone.<BR/><BR/>Mainly because of the Deeprun Tram, linking Ironforge and Stormwind City, and the district of Tinker Town, Ironforge is one of the most racially diverse cities in the Alliance world.<BR/>Dwarves predominate, of course, but you will find plenty of gnomes even outside of Tinker Town, and probably as many humans.<BR/>You will find almost no night elves however, as they probably prefer more natural and open spaced environments.<BR/>With the Council of Three Hammers uniting all three dwarven clans, Ironforge has recently welcomed Dark Iron dwarves and Wildhammer dwarves into Ironforge as well.</P><BR/><IMG align=\"CENTER\" src=\"Interface/AddOns/LoreLibrary/Images/crest_Dwarf\" /><BR/><BR/><BR/><BR/><BR/><P align=\"CENTER\"><BR/>Dwarven Crest</P><BR/></BODY></HTML>"}
{["title"] = "Gol'Bolar Quarry"		,["x"] = 76.25	,["y"] = 53.40	,["scale"] = 0.5	,["lore"] = "Gol'Bolar Quarry was once a dwarven excavation site but, in the middle of a dig, the dwarves uncovered one of the underground caverns belonging to the troggs.\nThe troggs pushed the dwarves out, and also took over the quarry outside of the mine."}
{["title"] = "Helm's Bed Lake"		,["x"] = 83.98	,["y"] = 51.93	,["lore"] = "Helm's Bed Lake is a smallish lake in southeastern Dun Morogh.\nAlthough the lake has mostly frozen over, a hole in the ice is maintained at all times in order to provide access to fresh water.\nSince the Cataclysm, angry water elementals have taken control over the lake."}
{["title"] = "North Gate Outpost"	,["x"] = 91.12	,["y"] = 37.78	,["scale"] = 0.5	,["lore"] = "The mountaineers stationed at the outpost are busily defending it from encroaching wildlife, and some dwarves have gone missing in the mountains in search of the more ferocious beasts."}
{["title"] = "Ironforge Airfield"	,["x"] = 77.69	,["y"] = 22.94	,["scale"] = 1.5	,["lore"] = "The Ironforge Airfield is an airfield located in a high mountain valley northeast of the dwarven capital city of Ironforge.\nIt has two landing strips, and several gnome pilots are there standing next to their planes or tinkering with them.\nAround the airfield, there are a series of dwarven buildings and structures.\nMountaineers from Ironforge patrol the area, and some members of the Stormpike Guard can be found here too.\nNorth of the airfield there is a gryphon roost, but it only connects to Gol'Bolar Quarry via a Flying Machine."}
