--
-- Elwynn Forest
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Stormwind City"			,["x"] = 32.20	,["y"] = 49.58	,["lore"] = "<HTML><BODY><P>Stormwind City is the capital city of the kingdom of Stormwind and the largest human city of Azeroth.<BR/>After the Third War, it has become one of the last great human cities.<BR/><BR/>No city better demonstrates human determination than Stormwind. Destroyed during the Horde’s initial invasion of Azeroth, Stormwind was painstakingly reconstructed by the Stonemasons’ Guild after the Second War. Parts of the city were razed again when Deathwing, the corrupted black Dragon Aspect, brutally attacked Stormwind, but the other undamaged districts are more beautiful than ever thanks to their hardworking inhabitants. From the magnificent Cathedral of Light, which serves as a major spiritual hub, to the awe-inspiring Valley of Heroes, which commemorates the sacrifices of Stormwind’s loyal champions, the city truly represents the courageous heart of humanity.</P><BR/><IMG align=\"CENTER\" src=\"Interface/AddOns/LoreLibrary/Images/crest_Human\" /><BR/><BR/><BR/><BR/><BR/><P align=\"CENTER\"><BR/>Human Crest</P><BR/></BODY></HTML>"}
{["title"] = "Goldshire"				,["x"] = 42.40	,["y"] = 65.67	,["lore"] = "Goldshire, along with Moonbrook, was taken in preparation of the Horde's sack of Stormwind Keep during the First Great War."}
{["title"] = "Westbrook Garrison"		,["x"] = 24.42	,["y"] = 74.43	,["lore"] = "Westbrook Garrison is considered by some to be the last bastion of order heading west of Stormwind.\nThe barracks is located in Forest's Edge on the western end of Elwynn Forest near the border with Westfall.\nBeyond the garrison lie the dry fields of Westfall, currently controlled by agents of the Defias Brotherhood and their dreaded mechanical harvesters.\nSouth of the garrison the forest is full of gnolls.\nBeyond, only a river separates Elwynn Forest from shadowy Duskwood.\nThe brave defenders of the garrison work night and day to protect the citizens of Elwynn from the dangers beyond the forest."}
{["title"] = "Fargodeep Mine"			,["x"] = 38.12	,["y"] = 83.71	,["lore"] = "The Fargodeep Mine is an abandoned gold mine located in Elwynn Forest, which has been overrun by kobolds.\n\nThe mine also functions as a barrier between the Stonefield Farm and Maclure Vineyards, two rival farms."}
{["title"] = "Jerod's Landing"			,["x"] = 48.35	,["y"] = 87.64	,["lore"] = "Jerod's Landing is a boat landing on the Elwynn Forest bank of the Nazferiti River.\nThe landing has was taken over by the Defias Brotherhood, and they used it to smuggle stolen goods from Redridge to Klaven's Tower in Westfall.\n\nWith the fall of the Defias Brotherhood, they have subsquently lost control of this point and now the dock is operated independently by the Dockmaster."}
{["title"] = "Tower of Azora"			,["x"] = 64.94	,["y"] = 69.96	,["lore"] = "The Tower of Azora is a small mage tower in eastern Elwynn Forest.\nThe tower is run by a number of servants of Azora, who all appear to be Gnomish, and who are in turn presided over by the Archmage of Azora, Theocritus.\nThe denizens of the tower are in a constant feud with the inhabitants of the Tower of Ilgalar in Redridge Mountains, ruled over by the evil sorcerer Morganth.\nThe two towers are constantly spying on one another through magical means.\n\nAn interview with the servants of Azora in the Gadgetzan Times reveals they are unable to wield magic and are somewhat resentful of the abilities of their master.\nIt also shows that many things straying too near the tower are adversely affected by its magical aura, so the servants often have to battle living buckets and mutant butterflies."}
{["title"] = "Heroes' Vigil"			,["x"] = 74.45	,["y"] = 51.63	,["lore"] = "Heroes' Vigil is the central area of the Stone Cairn Lake island in eastern Elwynn Forest.\nIt features a ring of stones, and a monument called the Stone of Remembrance which commemorates the dead from the orcs' sacking of Goldshire and other nearby regions during the First War."}
{["title"] = "Eastvale Logging Camp"	,["x"] = 80.9	,["y"] = 66.23	,["lore"] = "Eastvale Logging Camp is located in the far east of Elwynn Forest, under the very shadow of Redridge Mountains north of the main road.\nOrders for lumber are constantly streaming in from various buyers and the lumberjacks work against strict deadlines.\nBecause of its location in more hostile wilderness, wild animals are proving to be troublesome.\nWolves and bears in the area have become a menace, chasing off workers and threatening to cause delays in delivery deadlines.\nThe problem has become significant enough that the Stormwind Guard has become involved, recruiting adventurers to collect abandoned lumber and eradicate some of the aggressive wildlife."}
{["title"] = "Thunder Falls"			,["x"] = 24.96	,["y"] = 58.2	,["lore"] = "Thunder Falls is a narrow ravine, located in the mountains of north-western Elwynn Forest.\nA steep path leading up to the ravine can be found on the right of Mirror Lake's waterfall where there is a small rural cottage overrun by Bandits.\nIf the river is followed it will eventually wind into another waterfall that empties near the border of Westfall.\nThe bottom of the waterfall can be reached from above by carefully navigating through the hilly terrain.\n\nThunder Falls is quite unusual in the sense that it is a ravine with double-sided waterfall ends.\nThe falls are fed by a third, inaccessible waterfall from the cliffs on the northern side of the mountains."}
