--
-- Eversong Woods
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Silvermoon"				,["x"] = 56.66	,["y"] = 50.24	,["scale"] = 0.5	,["lore"] = "The crown jewel of the blood elves is their capital of Silvermoon City, nestled in the Eversong Woods in their ancestral lands of Quel'Thalas.\nAt the northernmost tip of the Eastern Kingdoms the beauty of the spires and thoroughfares of Silvermoon stand in stark contrast to the Dead Scar, the tainted path that Arthas tore through the city in his quest for power.\nThough nearly destroyed by Arthas' attack on the Sunwell, Silvermoon is once again a thriving city.\n\nMost recently, the rebirth of the Sunwell has lifted spirits among the elves, and they have continued to heal Silvermoon's scars in the hopes of returning their beloved capital to its former glory."}
{["title"] = "Duskwither Spire"			,["x"] = 68.92	,["y"] = 51.97	,["scale"] = 0.5	,["lore"] = "Duskwither Spire is a floating tower located in northeastern Eversong Woods.\nIt was once a magical academy run by Magister Duskwither, but fell into disrepair after the magister began looking into ill-fated ways to solve his race's addiction to magic."}
{["title"] = "Dead Scar"				,["x"] = 50.34	,["y"] = 50.49	,["lore"] = "The Dead Scar is a path of Blight that runs through the Kingdom of Quel'Thalas.\nDuring the Third War, the armies of the Scourge — led by the death knight Arthas Menethil, Crown Prince of Lordaeron — marched up this path from Lordaeron all the way to the Sunwell Plateau, killing everyone and destroying everything in its path.\nThe Dead Scar practically splits Quel'Thalas in half, all the way through Silvermoon itself.\n\nToday, the Dead Scar remains in the rebuilt Quel'Thalas, as a reminder to all who live there of the horrors committed by the Scourge — and as an incentive to seek their destiny beyond the Dark Portal."}
{["title"] = "Ruins of Silvermoon"		,["x"] = 45.44	,["y"] = 44.45	,["scale"] = 0.5	,["lore"] = "The area known as the Ruins of Silvermoon makes up the western half of Silvermoon City, the capital city of the blood elves and the former kingdom of Quel'Thalas.\nIt is split from the reconstructed eastern districts of Silvermoon City by the Dead Scar - the path taken by Arthas Menethil and the Scourge on their way to the Sunwell to resurrect the dead necromancer Kel'Thuzad.\n\nThe lack of energy from the Sunwell caused the high elf buildings in the Ruins of Silvermoon to fall apart."}
{["title"] = "Sunsail Anchorage"		,["x"] = 32.79	,["y"] = 69.49	,["scale"] = 0.5	,["lore"] = "Sunsail Anchorage is a port located in western Eversong Woods that has been completely taken over by the Wretched.\n\nA tall, three-story building is the only structure at the Anchorage.\nIn the center of the second story is a golden orb with an arm extending through the side of the building, through a slanted opening that curves up and around the building.\nAt the end of the arm is a curled loop.\nIt can be assumed, based on the construction and location of this building as well as the shape and placement of the opening the arm extends through, that this is intended to function as a sort of cargo crane or a boat lift for maintenance or unloading."}
{["title"] = "Fairbreeze Village"		,["x"] = 44.34	,["y"] = 71.1	,["lore"] = "Fairbreeze is the place where many young adventurers learn their trades, before venturing forth into Ghostlands and Tranquillien.\n\nWhen the Scourge attacked Quel'Thalas during the Third War, Sylvanas Windrunner retreated to the village and it was near here when she was killed and risen as an undead by Arthas."}
{["title"] = "East Sanctum"				,["x"] = 54.24	,["y"] = 71.03	,["lore"] = "The East Sanctum is one of three arcane sanctums in Eversong Woods.\nIn ruins, it rests close to the Dead Scar.\n\nNext to the sanctum is the blood elf researcher, Apprentice Mirveda.\nShe is trying to find a way to reverse the taint on the soil of the scar, but finds that it is irreversible."}
{["title"] = "Tor'Watha"				,["x"] = 69.88	,["y"] = 72.56	,["lore"] = "Tor'Watha is one of two forest troll areas of Eversong Woods. It is much larger than nearby Zeb'Watha.\nAt its eastern ridge once sat a colossal fortress of some kind with a massive set of gates.\nThe fortress was completely devoid of any inhabitants, and the forest trolls stayed in the camps below.\nIt was later deconstructed."}
{["title"] = "Runestone Shan'dor"		,["x"] = 55.35	,["y"] = 84.18	,["scale"] = 0.5	,["lore"] = "Runestone Shan'dor is one of the four remaining runestones in Quel'Thalas, located at the southern edge of Eversong Woods.\nIt has become deactivated, but can be reclaimed by using the energy from an arcane crystal.\nThe runestones were placed by high elven druids or magi to mark the boundaries of their new kingdom, Quel'Thalas, when the high elves had just found it.\n\nThese enchanted monuments created a magic barrier that prevented the trolls from penetrating into Quel'Thalasand to create a magical barrier that stopped the use of arcane magic from being sensed by the Burning Legion.\nThe Runestone Shan, when reactivated, is used to protect Eversong Woods from the effects of the Plague."}
{["title"] = "Runestone Falithas"		,["x"] = 44.0	,["y"] = 85.7	,["scale"] = 0.5	,["lore"] = "Runestone Falithas is one of the four remaining runestones in Quel'Thalas, located on the southern edge of Eversong Woods.\nOf the four, it is the only one to remain completely intact and functional.\nRunewarden Deryan tends to the runestone.\nThe runestones were placed by high elven druids or magi to mark the boundaries of their new kingdom, Quel'Thalas, when the high elves had just found it.\n\nThese enchanted monuments created a magic barrier that prevented the trolls from penetrating into Quel'Thalas and to create a magical barrier that stopped the use of arcane magic from being sensed by the Burning Legion.\nThe Runestone Falithas is now used to protect Eversong Woods from the effects of the Plague."}
{["title"] = "Scorched Grove"			,["x"] = 37.56	,["y"] = 86.36	,["lore"] = "|Hlinktype:linkstring|hLinktext|h\nThe Scorched Grove is an area of southwestern Eversong Woods that has been completely burned down by the blood elves in an attempt to halt the Scourge forces and the spreading of the soil-tainting blight.\nSuch extreme measures were thought to be necessary, as the runestones that protected the Woods were mostly destroyed by the Scourge.\nThe Grove is now populated by several aggressive treants who defiantly try to nurture life back into the burned soil."}
