--
-- Felwood
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Jaedenar"				,["x"] = 35.92	,["y"] = 59.26	,["scale"] = 2	,["lore"] = "Jaedenar is an area in Felwood that has been completely taken over by a sect of the Shadow Council.\nThe site of what is now Jaedenar lies on a series of ancient night elf ruins and two druidic barrow dens, on the western edge of Felwood.\nThe Shadow Council and its warlock agents took up residence here with the aim of spreading the region's corruption to the neighboring Ashenvale, thereby continuing the legion's plans for the destruction of Kalimdor.\nThe druids of the Emerald Circle are focusing on eradicating this threat and removing all cultists from the area before they can succeed with their twisted goals.\n\nJaedenar is apparently named after the eredar and leader of the Burning Crusade, Kil'jaeden."}
{["title"] = "Ruins of Constellas"	,["x"] = 37.01	,["y"] = 67.21	,["scale"] = 2	,["lore"] = "Xavathras, and his group of Jadefire satyr, inhabit the Ruins of Constellas.\nJudging by the remnants of the architecture, and the existence of a moonwell, it used to be one of the many night elven settlements near Mount Hyjal.\nThe moonwell has since become corrupted with Fel energy, and is being cultivated by Xavathras on behalf of Xavaric"}
{["title"] = "Deadwood Village"		,["x"] = 48.13	,["y"] = 88.99	,["scale"] = 3	,["lore"] = "Like most of their kin, the Furbolg of the Deadwood tribe have been corrupted and are hostile.\nDeadwood Village has been slightly expanded and more fortified.\nA wooden fence comprised of thick timbers encloses much of the Village and there are more sturdy structures inside."}
{["title"] = "Shatter Scar Vale"		,["x"] = 43.74	,["y"] = 40.40	,["scale"] = 3	,["lore"] = "Shatter Scar Vale is where many of the demonic infernals fell to Azeroth during the invasion of the Burning Legion during the Third War.\nStill-smoldering craters dot the vale, and demons still wander the scarred landscape."}
{["title"] = "Jadefire Run"			,["x"] = 42.42	,["y"] = 18.88	,["scale"] = 2	,["lore"] = "Jadefire Run was home of the most powerful satyr in Felwood.\nThe demons of Jadefire Run have seemingly abandoned the area in the Cataclysm and it has now been claimed by Whisperwind Healers.\nFeronas Sindweller, a demon hunter, is under the impression the healers are nothing more than the demons in disguise.\nThere also appears to be more traditional demonic architecture in the Run."}
{["title"] = "Irontree Woods"			,["x"] = 48.68	,["y"] = 25.20	,["lore"] = "Irontree Woods, once a peaceful forest glade, has been corrupted like the rest of Felwood by the demonic presence of the Burning Legion.\nThree Ancients - Hastat, Stoma and Vartrus, the great living trees of the night elves, have been petrified and remain permanently entombed within the Irontree Woods."}
{["title"] = "Timbermaw Hold"			,["x"] = 64.38	,["y"] = 10.00	,["lore"] = "When the corruption of the Burning Legion crept into the sacred forests of Kalimdor, the furbolgs fell under the corruptive influence of the Burning Legion.\nHowever, amidst the chaos and the madness, the Timbermaw tribe escaped the darkness that had fallen on Kalimdor.\nIn the safety of Timbermaw Hold, the furbolgs of the Timbermaw tribe weathered the storm, yet they were forced to watch helplessly as the forest they had loved so much was slowly turned into a twisted, festering perversion of its former self.\nThe corruption had sunk in deep, so that even long after Illidan had consumed the source of the corruption, a powerful warlock artifact called the Skull of Gul'dan, and vanquished the demons' leader Tichondrius, the taint on the woods still remained.\n\nThe furbolgs wary of all strangers, fearing that they may mistake them for their corrupted brethren and attack.\nHowever, the Timbermaw tribe are painfully aware that they will not last on their own; adventurers who seek out Timbermaw Hold in northern Felwood and prove themselves as friends of the Timbermaw tribe will learn that the furbolgs value their friends above all else.\nThough they possess no fine jewels or any worldly riches, the Timbermaw's shamanistic tradition is still strong.\nThey know much about the art of crafting armors from animal hides, and they are more than happy to share their healing/resurrection knowledge with friends of their tribe.\nThe Timbermaw's main concerns are putting an end to their corrupted brethren's suffering and finding a cure to heal the wounds the corruption of Felwood has inflicted upon the land, so that one day, the ancient forests will once again resound with the peaceful chants and the soft laughter of the children of the forest."}
{["title"] = "Talonbranch Glade"		,["x"] = 61.61	,["y"] = 26.56	,["lore"] = "Gilnean worgen were sent to Talonbranch in order to help the night elves with defending it from the attacking goblins from the Bilgewater Cartel; the Glade then turning into a prominent Gilnean outpost.\n\nPrior to the Cataclysm, Talonbranch Glade was a small night elven post, comprised of a house moonwell and various other Night elven scenery.\nAs of the Cataclysm, The Glade stretches down into the ramp entrances, boasting Gilnean structures, Gilnean flags, and a large tree similar to Tal'doren in the Blackwald.\n\nAccording to the leader Denmother Ulrica, several of the worgen (possibly Including herself) present in Talonbranch had been around since Velinde Starsong first summoned the Worgen with the Scythe of Elune.\nAs such some of the worgen present would be former Druids of the Scythe."}
{["title"] = "Whisperwind Grove"		,["x"] = 44.04	,["y"] = 28.40	,["lore"] = "Whisperwind Grove is a neutral town of the Emerald Circle, a largely autonomous branch of the Cenarion Circle.\nNotably, the land around Whisperwind Grove has been cleansed of corruption, and it is the location of the only uncorrupted moonwell in all of Felwood."}
