--
-- Ironforge
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Deeprum Tram"			,["x"] = 75.82	,["y"] = 51.00	,["lore"] = "King Bronzebeard turned to Azeroth's most esteemed engineer, High Tinker Gelbin Mekkatorque, who immediately began drafting designs for a grand subterranean railway system that would link Stormwind and Ironforge.\nHis vision has become reality, and the newly-built Deeprun Tram has developed into an indispensable link between the two great capitals, providing swift and safe transportation for thousands of their citizens, and bolstering military cooperation between the armies of these two proud Alliance strongholds.\n\nShortly after the petrification of Magni, Moira invaded Ironforge and closed the tram, isolating the dwarves in the city. Some time later, Varian led an elite strike team of SI:7 agents through the tram into Ironforge."}
{["title"] = "Tinker Town"			,["x"] = 70.63	,["y"] = 49.45	,["scale"] = 2	,["lore"] = "Originally, Tinker Town was just a small quarter of the city for gnomes visiting from Gnomeregan to use.\nWhen their clockwork city of Gnomeregan fell, it became the center of the gnomish court in exile (the Gnomeregan Exiles).\nPrior to the partial retaking of Gnomeregan, High Tinker Mekkatorque could be found here, along with his closest advisers."}
{["title"] = "Hall of Explorers"	,["x"] = 68.33	,["y"] = 20.06	,["scale"] = 2	,["lore"] = "The Hall of Explorers is home to the famed Ironforge Explorers' Guild (aka Explorer's League).\nEvery archaeological expedition the Alliance sends out is coordinated from here.\nIt also houses the the Library which houses a museum ran by Curator Thorius."}
{["title"] = "Forlorn Cavern"		,["x"] = 47.47	,["y"] = 12.13	,["scale"] = 2	,["lore"] = "The Forlorn Cavern is a long, winding road built around Ironforge's underground lake.\nIt's naturally dark and secluded nature makes it perfect for lots of shady deals."}
{["title"] = "Mystic Ward"			,["x"] = 28.73	,["y"] = 14.36	,["scale"] = 2	,["lore"] = "The Mystic Ward was established for the study of magic.\nThe Hall of Mysteries houses powerful magic users and is the center of arcane and divine power in the dwarven kingdom."}
{["title"] = "Commons"				,["x"] = 30.68	,["y"] = 66.70	,["scale"] = 2	,["lore"] = "The area known as the Commons is the main thoroughfare for trade in the city of Ironforge.\nIt contains the bank, Auction House and inn, as well as a few shops.\nThe Commons is always the busiest and most crowded portion of the city."}
{["title"] = "Military Ward"		,["x"] = 64.43	,["y"] = 79.04	,["scale"] = 2	,["lore"] = "The Military Ward serves as the command center for the Ironforge Military, as well as a center for all things martial.\nThe Hall of Arms is the center of dwarven military power and a hangar for both steam tanks and dwarven flying machines."}
{["title"] = "Great Forge"			,["x"] = 50.56	,["y"] = 42.70	,["scale"] = 2	,["lore"] = "The Great Forge is the heart and soul of dwarven culture, where all of their ingenious creations and weapons are made.\nIt was here, upon the The Great Anvil itself, that the legendary blade Ashbringer was forged by King Magni."}
{["title"] = "High Seat"			,["x"] = 40.74	,["y"] = 54.12	,["lore"] = "The High Seat is the former throne room of King Magni Bronzebeard in the dwarf city of Ironforge.\nAfter Magni Bronzebeard was turned to diamond, the leadership of Ironforge was assumed by the Council of Three Hammers: his daughter Moira Thaurissan, his brother Muradin Bronzebeard, and Falstad Wildhammer."}
{["title"] = "Old Ironforge"		,["x"] = 44.28	,["y"] = 51.96	,["lore"] = "After Magni Bronzebeard received earthen-related stone tablets from Brann in an attempt to learn about the pre-Cataclysm disturbances, Magni ordered the sealed gates of Old Ironforge to be opened for a ritual.\nThe key took two dwarves to lift, and it took a ladder for them to reach the lock.\nAfter venturing through the door, a linear path led Anduin, Muninn Magellas, Advisor Belgrum, High Priest Rohan and Reyna Stonebranch to a large cavern.\nA surprisingly new-looking carpeted path led upwards to a broad platform capable of holding a large group, and an unadorned stone path led downwards.\nWith an incantation scroll and a potion, Magni performed the ritual.\nWhile listening to the incantation, Anduin called this place the \"heart of the earth\".\nThe ritual seemingly worked, but turned him into a solid diamond statue."}
