--
-- Moonglade
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Nighthaven"				,["x"] = 48.43	,["y"] = 38.00	,["scale"] = 5	,["lore"] = ""}
{["title"] = "Stormrage Barrow Dens"	,["x"] = 68.03	,["y"] = 60.26	,["scale"] = 4	,["lore"] = "The Stormrage Barrow Dens are the sacred Barrow Dens of Moonglade where many of the Night Elf Druids slumber in the Emerald Dream.\nThe great druid Malfurion Stormrage, for whom the Barrow Dens are named, used to slumber deep within the dens.\n\nDuring the Third War, Malfurion was awakened by Tyrande to help fight Archimonde's forces.\nHe was sleeping in his Barrow Den and was almost destroyed by the Dreadlord Tichondrius' forces."}
{["title"] = "Shrine of Remulos"		,["x"] = 35.90	,["y"] = 41.55	,["lore"] = ""}
{["title"] = "Timbermaw Hold"			,["x"] = 35.68	,["y"] = 72.37	,["lore"] = "When the corruption of the Burning Legion crept into the sacred forests of Kalimdor, the furbolgs fell under the corruptive influence of the Burning Legion.\nHowever, amidst the chaos and the madness, the Timbermaw tribe escaped the darkness that had fallen on Kalimdor.\nIn the safety of Timbermaw Hold, the furbolgs of the Timbermaw tribe weathered the storm, yet they were forced to watch helplessly as the forest they had loved so much was slowly turned into a twisted, festering perversion of its former self.\nThe corruption had sunk in deep, so that even long after Illidan had consumed the source of the corruption, a powerful warlock artifact called the Skull of Gul'dan, and vanquished the demons' leader Tichondrius, the taint on the woods still remained.\n\nThe furbolgs wary of all strangers, fearing that they may mistake them for their corrupted brethren and attack.\nHowever, the Timbermaw tribe are painfully aware that they will not last on their own; adventurers who seek out Timbermaw Hold in northern Felwood and prove themselves as friends of the Timbermaw tribe will learn that the furbolgs value their friends above all else.\nThough they possess no fine jewels or any worldly riches, the Timbermaw's shamanistic tradition is still strong.\nThey know much about the art of crafting armors from animal hides, and they are more than happy to share their healing/resurrection knowledge with friends of their tribe.\nThe Timbermaw's main concerns are putting an end to their corrupted brethren's suffering and finding a cure to heal the wounds the corruption of Felwood has inflicted upon the land, so that one day, the ancient forests will once again resound with the peaceful chants and the soft laughter of the children of the forest."}
