--
-- Orgrimmar
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Ragefire Chasm"		,["x"] = 65.95	,["y"] = 50.70	,["level"] = 2 	,["scale"] = 5	,["lore"] = "Beneath the city of Orgrimmar lies this fiery chasm.\nA clan of troggs known as Ragefire Troggs had begun to appear in the chasm, from deep below the lava-filled tunnels.\nMagatha the Seer, of the tauren people, attempted to make peace with these creatures, but was met only with hostility.\nIt was clear that these troggs were not interested in diplomacy, and could potentially overwhelm the entire Horde if left unchecked.\n\nA sect of the mysterious Shadow Council had also taken refuge in this chasm.\nThis sect is known as the Searing Blade, and was led by Taragaman the Hungerer, a felguard; Jergosh the Invoker, a powerful warlock; and Bazzalan, a satyr.\nFrom their dark hiding place, they plotted to overthrow and destroy all that the Horde has built for themselves in these lands.\n\nAfter the Shattering, the Dark Shaman were formed and overtook Ragefire Chasm.\nThey cleared the presence of Searing Blade cultists and troggs, and used the latter to feed the enslaved beasts they brought from the Firelands.\nAlthough Warchief Garrosh Hellscream called on a number of shaman to use the elements as weapons against the Alliance, the chasm's inhabitants appear to be renegades.\nReports have surfaced that these shadowy figures are amassing a blistering army that could wreak havoc if unleashed upon Orgrimmar."}
{["title"] = "Brawl'gar Arena"		,["x"] = 70.34	,["y"] = 31.48	,["lore"] = "In the Brawl'gar Arena creatures and fighters from all over Azeroth and Outland have been gathered to participate in bloody arena deathmatches with heroes of the Horde.\n\nThe building housing the arena is also known as the Ring of Valor, notable for being the site of a duel between Thrall and Garrosh Hellscream during the Scourge Invasion."}
{["title"] = "Western Earthshrine"	,["x"] = 50.05	,["y"] = 37.84	,["lore"] = "The Western Earthshrine is a ritual circle erected by the Earthen Ring for use by the Horde.\nThe Earthshrine provides portals to Mount Hyjal, Vashj'ir, Deepholm, Uldum, Twilight Highlands and Tol Barad."}
{["title"] = "Skyway"				,["x"] = 49.42	,["y"] = 58.77	,["lore"] = "Orgrimmar Skyway is the city's main connetion to places across Azeroth.\n\nIts two zeppelin towers provide access to Thunderbluff, Tirisfal Glades near Undercity, Grom'gol in Stranglethorn Jungle, Warsong Hold in Borean Tundra"}
{["title"] = "Hall of Legends"		,["x"] = 40.27	,["y"] = 71.84	,["lore"] = "The Hall of Legends in Orgrimmar houses the secret armory of the Crimson Ring.\nThe weapons stored here come from every continent on Azeroth and the orcs' homeworld, Draenor.\nMany were taken as spoils of war and bear a proud history of battles lost and won."}
{["title"] = "Grommash Hold"		,["x"] = 49.45	,["y"] = 74.31	,["lore"] = "Grommash Hold is an enormous fortress located in the Valley of Strength in the orc capital of Orgrimmar.\nIt is named after the orcish hero Grom Hellscream, and serves as the administrative center of the Horde.\n\nBefore going hungry for power and being overthrown, Garrosh Hellscream, previous Warchief and son of Grom, resided here.\nNow the new Warchief, Vol'jin, and his advisors reside here."}
{["title"] = "Goblin Slums"			,["x"] = 40.11	,["y"] = 80.10	,["lore"] = "The Goblin Slums is the new district in Orgrimmar for the goblin refugees of Kezan.\nIt connects to the Valley of Spirits, and is an oily, dirty place - just the way the goblins like it.\n\nThe space now occupied by the Goblin Slums was part of the Valley of Spirits prior to the goblins joining the Horde.\nThe trolls moved further north in the valley, while the goblins were given this part of the valley to use as their own.\nThe slums are presided over by Boss Mida, who was added as a result of the Trade Princess Movement.\nOff-duty goblins can be found lounging around the pool area as well as waiting in line to withdraw their money from the bank, and off-duty Orgrimmar Grunts join them to converse and tell jokes.\n\nThere appears to be an oil-drilling operation within the lake, overseen by Environmental Engineer Linza; the surrounding area is filthy, with the pollution flowing downstream to the new Valley of Spirits."}
{["title"] = "Valley of Spirits"	,["x"] = 33.92	,["y"] = 68.27	,["lore"] = "Many parts of this valley sunk due to the Shattering and caused the large pool of water at the southern end to flow into the rest of the valley flooding a majority of it.\nThe two huts in that pool were destroyed and the area was given to the goblins of the Bilgewater Cartel, which they now call the Goblin Slums.\n\nMost of the orcish building survived here and continue to be used by their previous residents.\nThe Darkspear trolls have since been allowed to use this valley to build and expand upon.\nA tunnel to bypass the Goblin Slums was also dug through the mountain to the Valley of Wisdom.\n\nNear the end of Garrosh's rule, the district was put under martial law by the Kor'kron under orders from Garrosh himself due to the heavy troll population.\nThis was due to the recent rebellion against Garrosh's rule.\nCurfews were put in order, and Kor'kron guards actively patroled the district and arrested all suspicious individuals.\nSince his downfall, the Valley of Spirits has returned to its normal state."}
{["title"] = "Valley of Wisdom"		,["x"] = 40.76	,["y"] = 47.91	,["lore"] = "The Valley of Wisdom was once the location of Grommash Hold, where Warchief Thrall once resided in Orgrimmar.\nWhen the Cataclysm stuck much of the area changed as the land sunk in some places creating spots for pools to form.\n\nA few remains of Grommash Hold can still be seen where the tauren were allowed to setup huts and take this valley for their own use.\nThe armor of pit lord Mannoroth, which once rested on a tree here is now gone and the tree was destroyed."}
{["title"] = "Valley of Honor"		,["x"] = 67.78	,["y"] = 43.41	,["lore"] = "The Valley of Honor is the location for all things having to do with warfare in Orgrimmar.\nThe Ring of Valor arena is located here.\nThe Hall of the Brave houses the warrior guild, as well as all the city's battlemasters.\n\nThe Shattering has caused the land to shift in the valley.\nThis shifting has destroyed the once secluded pool of water and form a larger lake that flows throughout the valley.\n\nThe orcs have blown through the northern section of the valley to create an entrance to Azshara."}