--
-- Silvermoon City
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Sunfury Spire"		,["x"] = 55.66	,["y"] = 22.38	,["lore"] = "Sunfury Spire is Silvermoon City's palace.\nIt is here that Regent Lord Lor'themar Theron, ruler of Quel'Thalas, governs the country with the advice and counsel of Ranger General Halduron Brightwing and Grand Magister Rommath."}
{["title"] = "Hall of Blood"		,["x"] = 89.78	,["y"] = 37.49	,["lore"] = "The Hall of Blood is the headquarters of the Blood Knights, an order of blood elf paladins serving as the backbone of the Thalassian army.\n\nWith the strong support of the Magisters and the blood elven guard force, the former of which had a hand in their creation, the Blood Knights rose from unproven and scorned beginnings to become a popular group within sin'dorei society.\nThey are led by their matriarch, Lady Liadrin, who was the first of their order."}
{["title"] = "Reliquary"			,["x"] = 81.33	,["y"] = 63.88	,["lore"] = "The Reliquary is the headquarters of the blood elf organization zith the same name.\nThe Reliquary is a blood elven organization dedicated to the acquisition of powerful magical artifacts and studying the past, serving as the Horde counterpart to the Explorer's League.\n\nThe leader of the Reliquary, Tae'thelan Bloodwatcher, had spent a lifetime mastering the arts of sorcery and furthering his pursuit of magical knowledge.\nGathering like-minded blood elves, he formed the Reliquary, a primarily blood elven (but nonetheless multiracial) organization to acquire powerful magical artifacts for the sin'dorei and their Horde allies.\nTae'thelan maintains that such power not only should not be feared, but can be safety utilized with proper teaching, a creed he aims to instill in allies of the Reliquary.\nThrough these moderate and controlled methods, Tae'thelan ultimately aims to free his people from their magical addiction, and unite them as the proud, mighty race they once were."}
{["title"] = "Bazaar"				,["x"] = 61.18	,["y"] = 70.69	,["lore"] = "The Bazaar is Silvermoon's main hub of trade.\n\nNearby, two speakers adress the concerns af a gathering of concernd blood elves."}
{["title"] = "Dead Scar"			,["x"] = 54.30	,["y"] = 56.51	,["lore"] = "A gate protects the city from the Dead Scar, a path of Blight that runs through the Kingdom of Quel'Thalas\nThe Dead Scar cuts right through Silvermoon, cutting off part of the city."}
{["title"] = "The Sanctum"			,["x"] = 75.77	,["y"] = 44.03	,["lore"] = "The Sanctum is the warlock guild of Silvermoon City."}
{["title"] = "Shepherd's Gate"		,["x"] = 72.40	,["y"] = 85.95	,["lore"] = "The Shepherd's Gate serves as the main entry into Silvermoon from Eversong Woods.\nThe Shepherd's Gate was not the original entrance to the city.\nRemnants of the original entry can be seen down the Dead Scar, and a large, sealed gate in the Bazaar blocks the path."}
