--
-- Stormwind City
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Cathedral of Light"	,["x"] = 53.16	,["y"] = 51.50	,["scale"] = 2	,["lore"] = "The Cathedral is home to some of the most powerful and influential holy leaders in the world.\nDuthorian Rall is perhaps Stormwind City's most accomplished paladin.\nThe archbishop himself also resides within the hallowed chambers."}
{["title"] = "Stormwind Harbor"		,["x"] = 40.70	,["y"] = 47.28	,["scale"] = 2	,["lore"] = "Stormwind Harbor is one of the major ports for transport to both Northrend and Kalimdor, thereby connecting to Valiance Keep in the Borean Tundra and Rut'theran Village in Teldrassil."}
{["title"] = "Stormwind Cemetery"	,["x"] = 45.62	,["y"] = 29.42	,["scale"] = 2	,["lore"] = "Among those buried here is Queen Tiffin Wrynn, wife of King Varian.\nSome say you can talk to one of the deceased, if you can find his grave."}
{["title"] = "Deeprum Tram"			,["x"] = 67.69	,["y"] = 33.39	,["scale"] = 2	,["lore"] = "King Bronzebeard turned to Azeroth's most esteemed engineer, High Tinker Gelbin Mekkatorque, who immediately began drafting designs for a grand subterranean railway system that would link Stormwind and Ironforge.\nHis vision has become reality, and the newly-built Deeprun Tram has developed into an indispensable link between the two great capitals, providing swift and safe transportation for thousands of their citizens, and bolstering military cooperation between the armies of these two proud Alliance strongholds.\n\nShortly after the petrification of Magni, Moira invaded Ironforge and closed the tram, isolating the dwarves in the city. Some time later, Varian led an elite strike team of SI:7 agents through the tram into Ironforge."}
{["title"] = "Stormwind Keep"		,["x"] = 84.99	,["y"] = 32.71	,["scale"] = 2	,["lore"] = "The mighty Stormwind Keep is the seat of power of the human kingdom of Stormwind.\nThe residence of King Varian Wrynn and his son Anduin, the keep also houses the extensive Royal Library where nobles and scholars from across the known world research various topics."}
{["title"] = "Stormwind Park"		,["x"] = 44.84	,["y"] = 69.57	,["scale"] = 2	,["lore"] = "The Park used to be the district located in the western corner of Stormwind City. It was once a district devoted to leisure activities for Stormwind's populace until it became a refuge for visiting night elves, who found the comforting presence of nature a welcome respite from the vast stone thoroughfares of Stormwind proper. It was the only place in the Eastern Kingdoms where druid trainers resided. The night elves created a Moonwell in the center of the park square.\n\nThe Park was destroyed by Deathwing's visit to Stormwind, during the Shattering. When he attacked the city, the druid trainer Sheldras Moontree, priest trainer Nara Meideros, and Argos Nightwhisper were the only ones known to escape alive, with the rest unaccounted for. They have relocated down to Stormwind Harbor. All that remains of the Park are the ruins of The Old Barracks."}
{["title"] = "Wizard's Sanctum"		,["x"] = 49.86	,["y"] = 87.78	,["scale"] = 2	,["lore"] = "The Wizard's Sanctum, or Academy of Arcane Sciences, is a vine-covered tower that sits to the west of Stormwind City. For a long time, the Academy was considered to be a second-best school of magic compared to Dalaran, but since that region's destruction by the demons and undead, the northern mages fled to Stormwind and took up residence in the tower. It's full to bursting with mages, and some say it's difficult to get a word in edgeways with the differing opinions inside. Yet as it's the only magic school left in the east, few complain openly.\n\nSeemingly led by Maginor Dumas, the magi here strive to decipher arcane mysteries and uncover eldritch lore. Larimaine Purdue, the resident portalmancer, has created a rift portal deep in the Sanctum. She keeps the portal under close guard, and for now, will not let anyone venture through its swirling vortex. It is unknown where it leads to.\n\nThe Sanctum houses Stormwind wizards' guild, the Academy of the Arcane Sciences, and is currently one of the foremost centers of human arcane research and study today. Many high elves also seek refuge in the arcane halls, quenching their addiction and thirst for power in a safe environment."}
{["title"] = "SI:7"					,["x"] = 80.72	,["y"] = 61.29	,["scale"] = 2	,["lore"] = "SI:7, which stands for Stormwind Intelligence, is a secretive branch of King Varian's forces. It includes rogues specializing in special operations, espionage, assassination and stealth tactics.\n\nThe organization is currently led by Master Mathias Shaw. They have operatives all throughout the Eastern Kingdoms who carry out secret missions for Stormwind, such as Renzik \"The Shiv\" and Flint Shadowmore. They also have some operatives in the Kalimdor region, such as Andello Porter.\n\nThe black stallion is rumored to be favored by the SI:7 for night missions due to its dark coat."}
{["title"] = "Eastern Earthshrine"	,["x"] = 74.38	,["y"] = 18.42	,["scale"] = 2	,["lore"] = "The Eastern Earthshrine is a ritual circle erected by the Earthen Ring for use by the Alliance.\nThe Earthshrine provides portals to Mount Hyjal, Vashj'ir, Deepholm, Uldum, Twilight Highlands and Tol Barad."}
{["title"] = "Valley of Heroes"		,["x"] = 70.73	,["y"] = 85.77	,["lore"] = "The Valley of Heroes is a valley that lies before Stormwind Gate. A bridge of stone crosses the narrow moat and is the first sight of all who enter. \n\nStatues of Alliance heroes stand on either side of the road, welcoming visitors while providing an awe-inspiring warning. These heroes comprised the Alliance Expedition that travelled through the Dark Portal into Draenor to seal the dimensional rift from that side.\nOn the left are Kurdran Wildhammer, Thane of Aerie Peak, and the Archmage Khadgar of the Kirin Tor; on the right are Force Commander Danath Trollbane and Ranger-Captain Alleria Windrunner; at the end of the main road, just before it splits to enter Stormwind City proper, is General Turalyon, the expedition's military leader."}
{["title"] = "Stormwind Stockade"	,["x"] = 51.50	,["y"] = 68.31	,["lore"] = "Stormwind Stockade is a high-security prison complex, hidden beneath the canal district of Stormwind City.\nPresided over by Warden Thelwater, the Stockade is home to petty crooks, political insurgents, murderers and a score of the most dangerous criminals in the land.\n\nA large number of dangerous criminals, including some criminal masterminds and Defias mercenaries, are currently being held in the stockade.\nHowever, not so long ago, there was a revolt inside the dungeon, and the prisoners now keep the Stockade under their control."}
