--
-- Teldrassil
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Darnassus"				,["x"] = 38.59	,["y"] = 47.55	,["lore"] = "<HTML><BODY><P>Darnassus is the capital city of the night elves of the Alliance.<BR/>The high priestess, Tyrande Whisperwind, resides in the Temple of the Moon, surrounded by other sisters of Elune and her mate, the Arch-Druid Malfurion Stormrage.<BR/><BR/>In the aftermath of the Third War, the night elves had to adjust to their mortal existence.<BR/>Such an adjustment was far from easy, and there were many night elves who could not adjust to the prospects of aging, disease and frailty.<BR/>Seeking to regain their immortality, a number of wayward druids conspired to plant a special tree that would reestablish a link between their spirits and the eternal world.<BR/>With Malfurion Stormrage missing, Fandral Staghelm — the leader of those who wished to plant the new World Tree - became the new Arch-Druid.<BR/>In no time at all, he and his fellow druids had forged ahead and planted the great tree, Teldrassil, off the stormy coasts of northern Kalimdor.<BR/>Under their care, the tree sprouted up above the clouds.<BR/>Among the twilight boughs of the colossal tree, the wondrous city of Darnassus took root.<BR/>Darnassus was built to honor the survival of the night elven race.</P><BR/><IMG align=\"CENTER\" src=\"Interface/AddOns/LoreLibrary/Images/crest_NightElf\" /><BR/><BR/><BR/><BR/><BR/><P align=\"CENTER\"><BR/>Night Elven Crest</P><BR/></BODY></HTML>"}
{["title"] = "Wellspring Lake"		,["x"] = 44.37	,["y"] = 36.70	,["lore"] = "Wellspring Lake is a small lake northeast of Darnassus and southeast of The Oracle Glade in Teldrassil.\nFed by a natural spring deep within the land of the World Tree, this small lake is drained by the Wellspring River.\nPreviously a favored spot for night elven fishermen, the lake is now the home of corrupted timberlings."}
{["title"] = "Oracle Glade"			,["x"] = 39.16	,["y"] = 29.89	,["scale"] = 0.5	,["lore"] = "The Oracle Glade is a shrine in the northwestern area of Teldrassil.\nOne of the sacred moonwells lies there, as well as the magical Oracle Tree.\n\nThe Oracle Glade is the place where Malfurion Stormrage meditates."}
{["title"] = "Starbreeze Village"		,["x"] = 65.16	,["y"] = 50.93	,["lore"] = "Starbreeze Village lies south of Shadowglen and east of Dolanaar in Teldrassil.\nOnce a night elf village, Starbreeze is now overrun by corrupted furbolgs, an indication of the demonic infection that bleeds into Teldrassil."}
{["title"] = "Gnarlpine Hold"			,["x"] = 42.31	,["y"] = 69.34	,["lore"] = "Gnarlpine Hold was formally home to the Gnarlpine furbolgs.\nRecently, corruption has taken over the area and many demons are now present.\nA steady stream of demons flow out of the area to the north where Tarindrella and Teldrassil ancients meet for battle."}
{["title"] = "Rut'theran Village"		,["x"] = 55.48	,["y"] = 90.23	,["lore"] = "Rut'theran Village is an outpost port for the night elf city of Darnassus, located at the very bottom of the great tree Teldrassil.\nThere is a portal here that goes directly into Darnassus, as well as three docks with regular boats going to Exodar and Stormwind City.\n\nRut'theran Village originally had just one dock connected to Auberdine in Darkshore.\nDuring the Shattering, several parts of the village were destroyed and Auberdine was destroyed as well.\nSome of the services in Rut'theran Village were relocated to other parts of the now shattered island, and docks were added for the destinations previously reachable from Auberdine."}
