--
-- Undercity
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "King Terenas' tomb"	,["x"] = 65.97	,["y"] = 44.05	,["lore"] = "A memorial to king Terenas Menethil II, who was killed by his own son Arthas Menethil.\nAlthough the memorial appears to be a stone tomb, it was shown that after his death, Terenas was cremated.\nFurthermore, the urn containing his ashes was used to resurrect the Lich Kel'Thuzad.\nIt is unknown what happened to the King's remains after this point.\n\nThe memorial was crafted by the Alliance humans who once inhabited the old city, who risked everything to ensure that the memory of Lordaeron's last true king would not be forgotten."}
{["title"] = "Royal Quarter"		,["x"] = 56.94	,["y"] = 91.23	,["lore"] = "The Royal Quarter of the Undercity contains the throne room where the Dark Lady Sylvanas Windrunner controls her burgeoning empire of undeath.\nBragor Bloodfist has been assigned to this area to keep tabs on the Dark Lady and report all activity to the Warchief.\n\nThe Dreadlord Varimathras was found here alongside the Dark Lady prior to the Battle for the Undercity, where he tried to overthrow her by controlling a substantial part of the Forsaken faction.\nHe was eventually faced and defeated by Thrall and Sylvanas."}
{["title"] = "Apothecarium"			,["x"] = 53.28	,["y"] = 74.68	,["lore"] = "The Apothecarium is the home of the Royal Apothecary Society, a large-scale organization of undead dedicated to eradicating the \"taint of humanity\" from Lordaeron.\nThis is where the Forsaken work to brew their newest plagues, as well as creating more powerful abominations to serve in their armies.\nThis area is the domain of Master Apothecary Faranell and his alchemist minions.\n\nDuring the Battle of Undercity, the Alliance led by Varian Wrynn entered the Apothecarium and killed Putress here.\nThe king was horrified when he saw the laboratory."}
{["title"] = "Rogues' Quarter"		,["x"] = 81.38	,["y"] = 67.46	,["lore"] = "The Rogues' Quarter is home to many of the Forsaken's more shady characters and the rogues' guild."}
{["title"] = "Magic Quarter"		,["x"] = 81.04	,["y"] = 21.85	,["lore"] = "Magic Quarter is where the most arcane-inclined of the Forsaken come to research, learn new spells, and practice their arts, under the watchful eye of Bethor Iceshard."}
{["title"] = "War Quarter"			,["x"] = 51.96	,["y"] = 23.15	,["lore"] = "The War Quarter is where the Forsaken military is based.\nHere forsaken improve their combat skills on both dead and living opponents."}
{["title"] = "Sewers"				,["x"] = 45.38	,["y"] = 43.82	,["lore"] = "The Sewers are another way in and out of the city, which is guarded by abominations.\nThe tunnels allow flightpaths to leave and enter the city."}
{["title"] = "Trade Quarter"		,["x"] = 68.60	,["y"] = 48.03	,["lore"] = "As the name implies, the Trade Quarter is the central hub of trade of the Undercity."}
