--
-- Westfall
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Furlbrow's Pumpkin Farm"	,["x"] = 49.77	,["y"] = 19.81	,["lore"] = "Furlbrow's Pumpkin Farm (formerly known as Furlbrow's Pumpkin Patch) was one of the many farms in Westfall taken over by the Defias Brotherhood and their mechanical harvesters.\nThe killing machines used to patrol the fields before the Cataclysm, with the Defias taking up residence in the farm buildings.\nFarmer Furlbrow and his wife fled during that time to the road near the Jansen Stead in northern Westfall.\n\nAfter the events of the Cataclysm, the Furlbrows have apparently met an untimely demise near the Jansen Stead, their deaths currently under investigation.\nTheir farm was claimed by the Homeless Stormwind Citizens, Transients and similar individuals who can be found throughout the area."}
{["title"] = "Raging Chasm"			,["x"] = 38.36	,["y"] = 42.65	,["scale"] = 2	,["lore"] = "The Raging Chasm is a sinkhole created by the Cataclysm.\nWhat exactly happened to cause it, is still unknown.\nBecause of the rocks and trees flying around what appears to be a pillar of air, one could assume it is caused by angry Air Elementals."}
{["title"] = "Westfall Lighthouse"	,["x"] = 30.43	,["y"] = 85.71	,["lore"] = "The Westfall Lighthouse sits just off the coast on the far southern edge of Westfall.\nThe friendly ghost of Captain Grayson roams around this small island."}
{["title"] = "Dagger Hills"			,["x"] = 44.82	,["y"] = 80.29	,["lore"] = "The Dagger Hills is actually a ridge, sitting behind Moonbrook in Westfall.\nThe area is mostly devoid of life, with Grimbooze Thunderbrew being the only exception.\n\nBefore the fall of the Defias Brotherhood, this area was the home of their strongest members."}
{["title"] = "Moonbrook"			,["x"] = 43.41	,["y"] = 69.47	,["scale"] = 2	,["lore"] = "Prior to the coming of the orcs to Azeroth, Moonbrook served as the focal point of the farmlands of Westfall.\nDuring the First War, Moonbrook and its sister town Goldshire were the final two towns to fall to the Horde prior to the razing of Stormwind Keep.\nIt was rebuilt following the Alliance victory in the Second War.\n\nOne prominent family from Moonbrook is the Cooper family, who lived in a residence in the western part of the town.\nThe nearby mine was overseen by Foreman Thistlenettle, a member of the Explorers' League.\n\nFollowing successful efforts by the Defias to seize control of Westfall, Moonbrook was abandoned.\nFor a while, it was controlled by the Defias and used by them to access their main base of operations, the Deadmines.\nSince the defeat of Edwin VanCleef and the fall of the Brotherhood, Moonbrook has become home to a large number of vagrants."}
{["title"] = "Mortwake's Tower"		,["x"] = 70.61	,["y"] = 74.64	,["lore"] = "Mortwake's Tower, formerly Klaven's Tower, named after its rogue Defias master Klaven Mortwake, lies at the southeastern edge of Westfall near the river.\n\nSI:7 was previously scouting this mage tower for some time and sometimes covertly sought help from adventurous rogues to sneak in and gather intelligence.\nIt was a well known launching point for Defias activity such that it has also been called the \"Defias Tower\".\nKlaven's Tower was being used, along with Jerod's Landing in Elwynn Forest, in the smuggling of stolen goods from Redridge."}
{["title"] = "Sentinel Hill"		,["x"] = 56.33	,["y"] = 47.51	,["lore"] = "Sentinel Hill has been recently reinforced with the return of Gryan Stoutmantle and the Westfall Brigade from the war in Northrend.\nThe King has sent supplies, troops, and tanks in hopes of rebuilding the former breadbasket of the kingdom and to house the citizens of Stormwind whose homes were destroyed.\nFrom Sentinel Hill, the Westfall Brigade has been able to reclaim much of the lands, such as Moonbrook, the Furlbrow's Pumpkin Farm, and The Jansen Stead.\nThe town isn't finished yet, and cannot let the homeless that surround the town in yet."}
