--
-- Winterspring
--
-- {["title"] = ""			,["x"] = 0	,["y"] = 0	,["lore"] = ""}
-- /run print(GetPlayerMapPosition("player"))

{["title"] = "Timbermaw Hold"			,["x"] = 21.23	,["y"] = 46.11	,["scale"] = 0.5,["lore"] = "When the corruption of the Burning Legion crept into the sacred forests of Kalimdor, the furbolgs fell under the corruptive influence of the Burning Legion.\nHowever, amidst the chaos and the madness, the Timbermaw tribe escaped the darkness that had fallen on Kalimdor.\nIn the safety of Timbermaw Hold, the furbolgs of the Timbermaw tribe weathered the storm, yet they were forced to watch helplessly as the forest they had loved so much was slowly turned into a twisted, festering perversion of its former self.\nThe corruption had sunk in deep, so that even long after Illidan had consumed the source of the corruption, a powerful warlock artifact called the Skull of Gul'dan, and vanquished the demons' leader Tichondrius, the taint on the woods still remained.\n\nThe furbolgs wary of all strangers, fearing that they may mistake them for their corrupted brethren and attack.\nHowever, the Timbermaw tribe are painfully aware that they will not last on their own; adventurers who seek out Timbermaw Hold in northern Felwood and prove themselves as friends of the Timbermaw tribe will learn that the furbolgs value their friends above all else.\nThough they possess no fine jewels or any worldly riches, the Timbermaw's shamanistic tradition is still strong.\nThey know much about the art of crafting armors from animal hides, and they are more than happy to share their healing/resurrection knowledge with friends of their tribe.\nThe Timbermaw's main concerns are putting an end to their corrupted brethren's suffering and finding a cure to heal the wounds the corruption of Felwood has inflicted upon the land, so that one day, the ancient forests will once again resound with the peaceful chants and the soft laughter of the children of the forest."}
{["title"] = "Ruins of Kel'Theril"	,["x"] = 53.71	,["y"] = 57.45	,["lore"] = "The Ruins of Kel'Theril are the remnants of the great night elven city of Kel'Theril.\nIt was destroyed long ago during the Sundering, and it now lies in complete ruin, haunted by the tormented spirits of the Highborne who did not survive the disaster."}
{["title"] = "Frostsaber Rock"		,["x"] = 47.15	,["y"] = 18.16	,["scale"] = 2	,["lore"] = "Frostsaber Rock is a large jutting tor in the northern part of Winterspring.\nThis site is home to a great pride of wintersaber cats, ruled by the gargantuan female named Shy-Rotam\n\nThe Night Elves, who have an affinity with sabers, use the frostsabers as mounts and offer training to their Alliance friends."}
{["title"] = "Hidden Grove"			,["x"] = 62.24	,["y"] = 25.65	,["lore"] = "The Hidden Grove is home to the nearby moonkin who will protect it against trespassers."}
{["title"] = "Winterfall Village"		,["x"] = 66.79	,["y"] = 48.84	,["lore"] = "Winterfall Village is a large village of corrupted furbolgs in the far eastern area of Winterspring near Everlook.\nThe village was ruled by High Chief Winterfall, who resided in a small cave at the very top of the settlement.\nIt appears that High Chief Winterfall's position has been taken by Grolnar the Berserk, and now resides in the former chief's cave."}
{["title"] = "Everlook"				,["x"] = 59.72	,["y"] = 50.43	,["lore"] = "Everlook is a trading post run by the goblins of the Steamwheedle Cartel.\nAs the Cartel are neutral goblins, so is the Everlook a neutral town to both Horde and Alliance."}
{["title"] = "Mazthoril"				,["x"] = 55.09	,["y"] = 64.00	,["lore"] = "Before the Cataclysm, Mazthoril was under the control of the blue dragonflight lead by Haleh.  \nSince then the cavern was taken over by Umbranse the Spiritspeaker, a human mage who seeks to icrease is own power using dragon essences.\nThe cavern is filled with Arcane Tessaracts which are guarded my different types of hostile creatures.\n\nHaleh and some of the blue dragonflight has since moved to the nearby camp called Beryl Egress, planning to take back Mazthoril."}
{["title"] = "Frostwhisper Gorge"		,["x"] = 60.61	,["y"] = 87.65	,["scale"] = 4	,["lore"] = "Frostwhisper Gorge is a canyon in southern Winterspring, just north of Darkwhisper Gorge.\nIt is scattered with night elven ruins both at the bottom of the gorge and at the ridges above.\nA great bridge to Darkwhisper Gorge spanned across the chasm until the Shattering destroyed it.\n\nSeveral of the huge Frostmaul Preservers and Frostmaul Giants reside here, as well as Ice Avatars led by Frostilicus."}
