--
-- This file stores general information about the factions, not specific to any one faction.
-- The information here is as follows:
-- Faction ID 	-	Internal Name	-	External Name	-	Display (Yes/No)	-	Description
-- /run print(GetFactionInfoByID("ID"))
-- name, description, standingID, barMin, barMax, barValue, atWarWith, canToggleAtWar, isHeader, isCollapsed, hasRep, isWatched, isChild, factionID, hasBonusRepGain, canBeLFGBonus
--

{["ID"] = 1031,	["Name"] = "Sha'tari Skyguard",							["External"] = "Sha'tari Skyguard",					["Display"] = 1,	["Info"] = "An airborne military force created by Shattrath City to deal with the threats that loom in the highest reaches of Outland.",
{["ID"] = 1514,	["Name"] = "Adherents of Rukhmar",						["External"] = "Adherents of Rukhmar",				["Display"] = 1,	["Info"] = "Worshippers of the dread god Rukhmar, these vile filth seek to stain the world with the blood of their foes.",
{["ID"] = 1049,	["Name"] = "Troll, Amani",								["External"] = "Amani Trolls",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1515,	["Name"] = "Arakkoa Outcasts",							["External"] = "Arakkoa Outcasts",					["Display"] = 1,	["Info"] = "Working from the shadows, the Arakkoa Outcasts seek to bring a brighter tomorrow.",
{["ID"] = 1012,	["Name"] = "Ashtongue Deathsworn",						["External"] = "Ashtongue Deathsworn",				["Display"] = 1,	["Info"] = "The elite of the Broken tribe known as the Ashtongue, officially aligned with Illidan. The Deathsworn are Akama's most trusted lieutenants and are privy to their leader's mysterious motivations.",
{["ID"] = 1204,	["Name"] = "Avengers of Hyjal",							["External"] = "Avengers of Hyjal",					["Display"] = 1,	["Info"] = "Infuriated by the destruction wrought by the Lord of Flame, the Cenarion Circle seize the initiative, fighting back against Ragnaros and driving deep into the very heart of the Firelands.",
{["ID"] = 1177,	["Name"] = "Baradin's Wardens",							["External"] = "Baradin's Watchers",				["Display"] = 1,	["Info"] = "Once led by Duke Reginald Baradin II, this fierce army has historic ties to the island stronghold of Tol Barad.  They have joined the forces of the Alliance in an effort to repeal the Horde invaders and gain control of this strategic island.",
{["ID"] = 34,	["Name"] = "Orc, Blackrock",							["External"] = "Blackrock Orcs",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1129,	["Name"] = "Furbolg, Blackwood",						["External"] = "Blackwood Furbolg",					["Display"] = 1,	["Info"] = "",
{["ID"] = 81,	["Name"] = "Thunder Bluff",								["External"] = "Bloodhoof Tauren",					["Display"] = 1,	["Info"] = "Baine Bloodhoof leads his people, the proud Tauren, from this mighty Horde capital.",
{["ID"] = 929,	["Name"] = "Bloodmaul Clan",							["External"] = "Bloodmaul Clan",					["Display"] = 1,	["Info"] = "",
{["ID"] = 87,	["Name"] = "Bloodsail Buccaneers",						["External"] = "Bloodsail Buccaneers",				["Display"] = 1,	["Info"] = "These bloodthirsty corsairs are the bane of many a merchant in the high seas.  Sworn enemies of Booty Bay.",
{["ID"] = 26,	["Name"] = "Troll, Bloodscalp",							["External"] = "Bloodscalp Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 21,	["Name"] = "Booty Bay",									["External"] = "Booty Bay",							["Display"] = 1,	["Info"] = "This booming coastal city is run by Baron Revilgaz of the Blackwater Raiders.  Mortal enemies of the Bloodsail Buccaneers and part of the Steamwheedle Cartel.",
{["ID"] = 85,	["Name"] = "Quilboar, Bristleback",						["External"] = "Bristleback Quillboar",				["Display"] = 1,	["Info"] = "",
{["ID"] = 955,	["Name"] = "Broken",									["External"] = "Broken",							["Display"] = 1,	["Info"] = "",
{["ID"] = 942,	["Name"] = "Cenarion Expedition",						["External"] = "Cenarion Expedition",				["Display"] = 1,	["Info"] = "An exploratory force sent to Outland by the Cenarion Circle to study surviving life forms.  The Cenarion Expedition has quickly gained in size and autonomy since the opening of the Dark Portal.",
{["ID"] = 1731,	["Name"] = "Council of Exarchs",						["External"] = "Council of Exarchs",				["Display"] = 1,	["Info"] = "Under the leadership of five powerful exarchs, the draenei of Draenor have prospered in a savage world.",
{["ID"] = 1900,	["Name"] = "Court of Farondis",							["External"] = "Court of Farondis",					["Display"] = 1,	["Info"] = "The ghostly Court of Farondis and its allies continue the fight against an onslaught of invaders on the cursed island of Azsuna.",
{["ID"] = 61,	["Name"] = "Dalaran",									["External"] = "Dalaran",							["Display"] = 1,	["Info"] = "",
{["ID"] = 48,	["Name"] = "Dark Iron Dwarves",							["External"] = "Dark Iron Dwarves",					["Display"] = 1,	["Info"] = "",
{["ID"] = 909,	["Name"] = "Darkmoon Faire",							["External"] = "Darkmoon Faire",					["Display"] = 1,	["Info"] = "A carnival that showcases the weird and the extraordinary, located on a mysterious island only accessible for the first week of every month.",
{["ID"] = 1447,	["Name"] = "Darkspear Trolls",							["External"] = "Darkspear Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 530,	["Name"] = "Darkspear Trolls",							["External"] = "Darkspear Trolls",					["Display"] = 1,	["Info"] = "This tribe of exiled trolls has joined forces with Thrall and the Horde.  They now call Durotar their home, which they share with their orc allies.",
{["ID"] = 69,	["Name"] = "Darnassus",									["External"] = "Darnassus",							["Display"] = 1,	["Info"] = "This Alliance capital is populated by Night Elves and is located in the Island of Teldrassil.  Ruled by the Priestess of the Moon, Tyrande Whisperwind.",
{["ID"] = 111,	["Name"] = "Quilboar, Deathshead",						["External"] = "Deathshead Quillboar",				["Display"] = 1,	["Info"] = "",
{["ID"] = 15,	["Name"] = "Defias Brotherhood",						["External"] = "Defias Brotherhood",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1172,	["Name"] = "Dragonmaw Clan",							["External"] = "Dragonmaw Clan",					["Display"] = 1,	["Info"] = "This wayward orc clan was once empowered by Deathwing himself to enslave red dragons, including Alexstrasza.  Currently less numerous and powerful, the Dragonmaw make their home in the Twilight Highlands.",
{["ID"] = 52,	["Name"] = "Orc, Fel Dragonmaw",						["External"] = "Fel Dragonmaw Clan",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1107,	["Name"] = "Troll, Drakkari",							["External"] = "Drakkari Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1883,	["Name"] = "Dreamweavers",								["External"] = "Dreamweavers",						["Display"] = 1,	["Info"] = "The druids and their allies in Val'sharah have guarded the Emerald Dream since time immemorial.",
{["ID"] = 1910,	["Name"] = "Drogbar",									["External"] = "Drogbar",							["Display"] = 1,	["Info"] = "",
{["ID"] = 956,	["Name"] = "Ethereum",									["External"] = "Ethereum",							["Display"] = 1,	["Info"] = "",
{["ID"] = 577,	["Name"] = "Everlook",									["External"] = "Everlook",							["Display"] = 1,	["Info"] = "This trading post is run by the goblins of the Steamwheedle Cartel and it sits in the crossroads of Winterspring's main trade routes.",
{["ID"] = 930,	["Name"] = "Exodar",									["External"] = "The Exodar",						["Display"] = 1,	["Info"] = "The naaru vessel that brought the draenei to Azeroth.  Though stranded in the Azuremyst Isles, it acts as a home city for this noble race.",
{["ID"] = 1068,	["Name"] = "Explorers' League",							["External"] = "Explorer's League",					["Display"] = 1,	["Info"] = "This organization seeks to find the origin of the dwarven race by collecting Titan artifacts.  Their most recent research has led them to various archeological sites in Northrend.",
{["ID"] = 923,	["Name"] = "Farstriders",								["External"] = "The Farstriders",					["Display"] = 1,	["Info"] = "",
{["ID"] = 943,	["Name"] = "Fel Orc",									["External"] = "Fel Orcs",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1228,	["Name"] = "Forest Hozen",								["External"] = "Forest Hozen",						["Display"] = 1,	["Info"] = "A spirited, violent, and short-lived race of monkey people",
{["ID"] = 937,	["Name"] = "Troll, Forest",								["External"] = "Forest Trolls",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1104,	["Name"] = "Frenzyheart Tribe",							["External"] = "Frenzyheart Tribe",					["Display"] = 1,	["Info"] = "Driven from their lands by the Scourge, this fierce tribe of wolvar stumbled upon Sholazar Basin, where they intend to make their new home.  Their aggressive nature has put them at odds with the various gorloc tribes known collectively as the Oracles.",
{["ID"] = 1121,	["Name"] = "Frost Vrykul",								["External"] = "Frost Vrykul",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1496,	["Name"] = "Frostfire Ogres",							["External"] = "Frostfire Ogres",					["Display"] = 1,	["Info"] = "Frostfire ogres are not interesting, but they do like to argue.",
{["ID"] = 33,	["Name"] = "Troll, Frostmane",							["External"] = "Frostmane Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1089,	["Name"] = "Furbolg, Frostpaw",							["External"] = "Frostpaw Furbolg",					["Display"] = 1,	["Info"] = "",
{["ID"] = 729,	["Name"] = "Frostwolf Clan",							["External"] = "Frostwolf Clan (Azeroth)",			["Display"] = 1,	["Info"] = "The Frostwolf Clan seeks to drive out the dwarves of the Stormpike Expedition from Alterac Valley.",
{["ID"] = 1445,	["Name"] = "Frostwolf Orcs",							["External"] = "Frostwolf Clan (Draenor)",			["Display"] = 1,	["Info"] = "The Frostwolf orcs of Frostfire Ridge are a tight-knit family of brutal warriors, well equipped to deal with the savage realities of Draenor.",
{["ID"] = 369,	["Name"] = "Gadgetzan",									["External"] = "Gadgetzan",							["Display"] = 1,	["Info"] = "Capital of the Steamwheedle Cartel and home to goblinhood's finest engineers, alchemists and merchants.",
{["ID"] = 91,	["Name"] = "Centaur, Galak",							["External"] = "Galak Centaur",						["Display"] = 1,	["Info"] = "",
{["ID"] = 92,	["Name"] = "Gelkis Clan Centaur",						["External"] = "Gelkis Centaur",					["Display"] = 1,	["Info"] = "These centaur have made their home in the southern region of Desolace.  Mortal enemies of the Magram Centaur.",
{["ID"] = 1134,	["Name"] = "Gilneas",									["External"] = "Gilneas",							["Display"] = 1,	["Info"] = "The people of Gilneas are a nation of survivors.  Having walled themselves off from the rest of humanity, they must now face new threats from within.",
{["ID"] = 54,	["Name"] = "Gnomeregan",								["External"] = "Gnomeregan",						["Display"] = 1,	["Info"] = "The former denizens of Gnomeregan, now living in New Tinkertown and in league with the Alliance.",
{["ID"] = 1161,	["Name"] = "Grimtotem",									["External"] = "Grimtotem Tauren",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1158,	["Name"] = "Guardians of Hyjal",						["External"] = "Guardians of Hyjal",				["Display"] = 1,	["Info"] = "Faced with the impending devastation of Mount Hyjal, the most powerful members of the Cenarion Circle have joined forces with their Emerald Dragonflight allies to fend off Ragnaros' elemental hordes and the Twilight's Hammer.",
{["ID"] = 1847,	["Name"] = "Hand of the Prophet",						["External"] = "Hand of the Prophet",				["Display"] = 1,	["Info"] = "Yrel has assembled the remaining Exarchs and is calling for a crusade in Velen's name. Together they are working to establish a foothold in Tanaan Jungle and to overthrow Gul'dan.",
{["ID"] = 409,	["Name"] = "Harpy",										["External"] = "Harpies",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1178,	["Name"] = "Hellscream's Reach",						["External"] = "Hellscream's Reach",				["Display"] = 1,	["Info"] = "Hellscream's Reach is an elite Horde regiment comprised solely of veterans of multiple tours of duty.   Handpicked by Garrosh himself, he has commanded them to take complete control of Tol Barad.  Failure is not an option.",
{["ID"] = 1680,	["Name"] = "Highmaul",									["External"] = "Highmaul Ogres",					["Display"] = 1,	["Info"] = "Highmaul ogres like togas and gladiator fights.",
{["ID"] = 1828,	["Name"] = "Highmountain Tribe",						["External"] = "Highmountain Tauren",				["Display"] = 1,	["Info"] = "The Highmountain Tribe has dwindled in numbers over the years, and with the drogbar threat looming, seek new allies to save their homeland.",
{["ID"] = 71,	["Name"] = "Hillsbrad Militia",							["External"] = "Hillsbrad Militia",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1372,	["Name"] = "Honeydew Village",							["External"] = "Honeydew Village",					["Display"] = 1,	["Info"] = "",
{["ID"] = 946,	["Name"] = "Honor Hold",								["External"] = "Honor Hold ",						["Display"] = 1,	["Info"] = "Vestiges of the Sons of Lothar, veterans of the Alliance that first came into Draenor, have steadfastly held on to this Hellfire outpost.  They are now joined by the armies from Stormwind and Ironforge.",
{["ID"] = 1052,	["Name"] = "Horde Expedition",							["External"] = "Horde Expedition",					["Display"] = 1,	["Info"] = "The combined forces of the Horde in Northrend, spearheaded by the Warsong Offensive.",
{["ID"] = 749,	["Name"] = "Hydraxian Waterlords",						["External"] = "Hydraxian Waterlords",				["Display"] = 1,	["Info"] = "These elementals have made their home on the islands east of Azshara.  Sworn enemies of the armies of Ragnaros.",
{["ID"] = 1076,	["Name"] = "Iron Dwarves",								["External"] = "Iron Dwarves",						["Display"] = 1,	["Info"] = "",
{["ID"] = 47,	["Name"] = "Ironforge",									["External"] = "Ironforge",							["Display"] = 1,	["Info"] = "This Alliance capital is the pride of the Dun Morogh dwarves.  Home to King Magni.",
{["ID"] = 869,	["Name"] = "Jaedenar",									["External"] = "Jaedenar",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1888,	["Name"] = "Jandvik Vrykul",							["External"] = "Jandvik Vrykul",					["Display"] = 1,	["Info"] = "",
{["ID"] = 72,	["Name"] = "Stormwind",									["External"] = "Stormwind",							["Display"] = 1,	["Info"] = "One of the last bastions of human power, this Alliance capital is ruled by the prodigal king, Varian Wrynn.",
{["ID"] = 1098,	["Name"] = "Knights of the Ebon Blade",					["External"] = "Knights of the Ebon Blade",			["Display"] = 1,	["Info"] = "Freed from the grasp of the Lich King, his former Death Knights have regrouped against him under the banner of Highlord Darion Mograine.",
{["ID"] = 90,	["Name"] = "Centaur, Kolkar",							["External"] = "Kolkar Centaur",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1443,	["Name"] = "Kor'kron",									["External"] = "The Kor'kron",						["Display"] = 1,	["Info"] = "",
{["ID"] = 978,	["Name"] = "Kurenai",									["External"] = "Kurenai",							["Display"] = 1,	["Info"] = "Draenei for "redeemed."  These Broken have escaped the grasp of their various slavers in Outland and have made their home in Nagrand.  It is there that they seek to rediscover their destiny.",
{["ID"] = 39,	["Name"] = "Kurzen's Mercenaries",						["External"] = "Kurzen's Mercenaries",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1912,	["Name"] = "Kvaldir",									["External"] = "Kvaldir Vrykul",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1708,	["Name"] = "Laughing Skull Orcs",						["External"] = "Laughing Skull Clan",				["Display"] = 1,	["Info"] = "The Laughing Skull clan calls the most savage reaches of Draenor home, laughing maniacally at the impending annihilation they face from every side.",
{["ID"] = 53,	["Name"] = "Gnome - Leper",								["External"] = "Leper Gnomes",						["Display"] = 1,	["Info"] = "",
{["ID"] = 45,	["Name"] = "Lost Ones",									["External"] = "Lost Ones",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1011,	["Name"] = "Lower City",								["External"] = "Lower City",						["Display"] = 1,	["Info"] = "The refugees of Shattrath come from diverse backgrounds and races.  Word of helpful deeds spreads quickly among the Denizens of Lower City.",
{["ID"] = 93,	["Name"] = "Magram Clan Centaur",						["External"] = "Magram Centaur",					["Display"] = 1,	["Info"] = "These centaur have made their home in the eastern region of Desolace.  Mortal enemies of the Gelkis Centaur.",
{["ID"] = 94,	["Name"] = "Maraudine",									["External"] = "Maraudine",							["Display"] = 1,	["Info"] = "",
{["ID"] = 912,	["Name"] = "Might of Kalimdor",							["External"] = "Might of Kalimdor",					["Display"] = 1,	["Info"] = "",
{["ID"] = 51,	["Name"] = "Gnoll - Mosshide",							["External"] = "Mosshide Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 78,	["Name"] = "Gnoll - Mudsnout",							["External"] = "Mudsnout Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 60,	["Name"] = "Naga",										["External"] = "Naga",								["Display"] = 1,	["Info"] = "",
{["ID"] = 1038,	["Name"] = "Ogri'la",									["External"] = "Ogri'la",							["Display"] = 1,	["Info"] = "The enlightened denizens of Ogri'la have made their dwelling in the western Blade's Edge Mountains, where proximity to apexis crystals has caused them to transcend their brutish ogre nature.",
{["ID"] = 1849,	["Name"] = "Order of the Awakened",						["External"] = "Order of the Awakened",				["Display"] = 1,	["Info"] = "Survivors of a grisly civil war, these beleaguered arakkoans hope the reclamation of apexis artifacts will hold the key to peacefully rebuilding their civilization.",
{["ID"] = 1271,	["Name"] = "Order of the Cloud Serpent",				["External"] = "Order of the Cloud Serpent",		["Display"] = 1,	["Info"] = "Guardians of the East Temple",
{["ID"] = 76,	["Name"] = "Orgrimmar",									["External"] = "Orgrimmar",							["Display"] = 1,	["Info"] = "Founded by Thrall, this Horde capital city is home to many of the proud orc clans of Durotar.",
{["ID"] = 1371,	["Name"] = "Paw'don Village",							["External"] = "Paw'don Village",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1242,	["Name"] = "Pearlfin Jinyu",							["External"] = "Pearlfin Jinyu",					["Display"] = 1,	["Info"] = "A reserved, methodical race of fish people.",
{["ID"] = 470,	["Name"] = "Ratchet",									["External"] = "Rachet Goblins",					["Display"] = 1,	["Info"] = "Part of the Steamwheedle Cartel, this goblin city provides a neutral haven for those that wish to trade goods and services in the Barrens.",
{["ID"] = 1173,	["Name"] = "Ramkahen",									["External"] = "Ramkahen",							["Display"] = 1,	["Info"] = "The cat-like people of Ramkahen are the descendants of the Tol'vir, guardians of Uldum.  Though they've lost their stone bodies, protecting the secrets of the titans is still a part of their rigid tradition.",
{["ID"] = 349,	["Name"] = "Ravenholdt",								["External"] = "Ravenholdt",						["Display"] = 1,	["Info"] = "This guild of thieves and assassins welcomes only those of extraordinary prowess into its fold.  Sworn rivals of the Syndicate.",
{["ID"] = 1028,	["Name"] = "Ravenswood Ancients",						["External"] = "Ravenswood Ancients",				["Display"] = 1,	["Info"] = "",
{["ID"] = 109,	["Name"] = "Quilboar, Razorfen",						["External"] = "Razorfen Quillboar",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1088,	["Name"] = "Furbolg, Redfang",							["External"] = "Redfang Furbolg",					["Display"] = 1,	["Info"] = "",
{["ID"] = 17,	["Name"] = "Gnoll - Redridge",							["External"] = "Redridge Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 16,	["Name"] = "Gnoll - Riverpaw",							["External"] = "Riverpaw Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 57,	["Name"] = "Gnoll - Rothide",							["External"] = "Rothide Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1710,	["Name"] = "Sha'tari Defense",							["External"] = "Sha'tari Defense",					["Display"] = 1,	["Info"] = "The defenders of Shattrath struggle to regain control of their capital city, having been betrayed from within.",
{["ID"] = 18,	["Name"] = "Gnoll - Shadowhide",						["External"] = "Shadowhide Gnolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1520,	["Name"] = "Shadowmoon Exiles",							["External"] = "Shadowmoon Exiles",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1508,	["Name"] = "Shadowmoon Orcs",							["External"] = "Shadowmoon Clan",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1077,	["Name"] = "Shattered Sun Offensive",					["External"] = "Shattered Sun Offensive",			["Display"] = 1,	["Info"] = "Shattrath City's final push against Prince Kael'thas' operations in the Sunwell.",
{["ID"] = 629,	["Name"] = "Shatterspear Trolls",						["External"] = "Shatterspear Trolls",				["Display"] = 1,	["Info"] = "",
{["ID"] = 809,	["Name"] = "Shen'dralar",								["External"] = "Shen'Dralar",						["Display"] = 1,	["Info"] = "A remnant of the once powerful elves living in Dire Maul, yet still wise and knowledgeable about great secrets. ",
{["ID"] = 249,	["Name"] = "Silithid",									["External"] = "Silithid",							["Display"] = 1,	["Info"] = "",
{["ID"] = 911,	["Name"] = "Silvermoon City",							["External"] = "Silvermoon City",					["Display"] = 1,	["Info"] = "The capital of Quel'Thalas, home of the blood elves.  Though nearly destroyed by Arthas' attack on the Sunwell, Silvermoon is once again a thriving city.",
{["ID"] = 890,	["Name"] = "Silverwing Sentinels",						["External"] = "Silvermoon Sentinels",				["Display"] = 1,	["Info"] = "Staunch defenders of Ashenvale, locked in battle against the Warsong Outriders in Warsong Gulch.",
{["ID"] = 27,	["Name"] = "Troll, Skullsplitter",						["External"] = "Skullsplitter Trolls",				["Display"] = 1,	["Info"] = "",
{["ID"] = 573,	["Name"] = "Southsea Freebooters",						["External"] = "Southsea Freebooters",				["Display"] = 1,	["Info"] = "",
{["ID"] = 970,	["Name"] = "Sporeggar",									["External"] = "Sporeggar",							["Display"] = 1,	["Info"] = "The sporelings are a mostly peaceful race of mushroom-men native to Outland. Their home is located in the southern bogs of Zangarmarsh. ",
{["ID"] = 169,	["Name"] = "Steamwheedle Cartel",						["External"] = "Steamwheedle Cartel",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1732,	["Name"] = "Steamwheedle Draenor Expedition",			["External"] = "Steamwheedle Draenor Expedition",	["Display"] = 1,	["Info"] = "Draenor is a long of infinite opportunity, and very little competition.",
{["ID"] = 1711,	["Name"] = "Steamwheedle Preservation Society",			["External"] = "Steamwheedle Preservation Society",	["Display"] = 1,	["Info"] = "The goblins of the Steamwheedle Preservation Society seek to liberate relics from the ogres of Nagrand with the noble intention of selling them to the highest bidder.",
{["ID"] = 961,	["Name"] = "Stillpine Furbolg",							["External"] = "Stillpine Furbolg",					["Display"] = 1,	["Info"] = "",
{["ID"] = 730,	["Name"] = "Stormpike Guard",							["External"] = "Stormpike Guard",					["Display"] = 1,	["Info"] = "The Stormpike Dwarves have set up residence in Alterac Valley, where they're locked in battle with the Frostwolf Orcs.",
{["ID"] = 750,	["Name"] = "Sulfuron Firelords",						["External"] = "Sulfuron Firelords",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1388,	["Name"] = "Sunreaver Onslaught",						["External"] = "Sunreaver Onslaught",				["Display"] = 1,	["Info"] = "Outcast from Dalaran, the Sunreaver Onslaught fight to obtain powerful mogu artifacts from among the ruins of Thunder Isle, and to secure their future if the Horde falls to anarchy.",
{["ID"] = 70,	["Name"] = "Syndicate",									["External"] = "Syndicate",							["Display"] = 1,	["Info"] = "A primarily human criminal organization that operates mostly out of the Alterac Mountains and Hillsbrad Foothills.",
{["ID"] = 932,	["Name"] = "The Aldor",									["External"] = "The Aldor",							["Display"] = 1,	["Info"] = "An ancient order of draenei priests once run by Velen, the Aldor are currently led by High Priestess Ishanah.  They are servants of the naaru in Shattrath City known as the Sha'tar.  Rivals of the Scryers.",
{["ID"] = 469,	["Name"] = "Alliance",									["External"] = "The Alliance",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1302,	["Name"] = "The Anglers",								["External"] = "The Anglers",						["Display"] = 1,	["Info"] = "The Anglers are a group of Pandaren fisherman that hope to feed their people and grow their knowledge of fishing.",
{["ID"] = 1106,	["Name"] = "Argent Crusade",							["External"] = "The Argent Crusade",				["Display"] = 1,	["Info"] = "Led by Tirion Fordring, the Argent Crusade combines the reformed Order of the Silver Hand with the Argent Dawn in one final push against the forces of the Lich King.",
{["ID"] = 529,	["Name"] = "Argent Dawn",								["External"] = "The Argent Dawn",					["Display"] = 1,	["Info"] = "An organization focused on protecting Azeroth from the threat of the Scourge.  Strongholds of the Argent Dawn can be found in the Eastern and Western Plaguelands.",
{["ID"] = 1156,	["Name"] = "The Ashen Verdict",							["External"] = "The Ashen Verdict",					["Display"] = 1,	["Info"] = "Under a pact by Tirion Fordring and Darion Mograine, the Argent Crusade and the Knights of the Ebon Blade have set aside their differences during the attack on Icecrown Citadel until the Lich King is slain.",
{["ID"] = 1341,	["Name"] = "The August Celestials",						["External"] = "The August Celestials",				["Display"] = 1,	["Info"] = "These brave Pandaren defend the temples of Pandaria from the evils of the Sha.",
{["ID"] = 1133,	["Name"] = "Bilgewater Cartel",							["External"] = "The Bilgewater Cartel",				["Display"] = 1,	["Info"] = "Run by the ruthless Trade Prince Gallywix, the Bilgewater Cartel is the most powerful trading company on the Isle of Kezan. From their headquarters at Bilgewater Port, the cartel dominates trade all over the South Seas.",
{["ID"] = 80,	["Name"] = "Dragonflight, Black",						["External"] = "The Black Dragonflight",			["Display"] = 1,	["Info"] = "",
{["ID"] = 1359,	["Name"] = "The Black Prince",							["External"] = "The Black Prince",					["Display"] = 1,	["Info"] = "Black Prince Wrathion is the last of the black dragons. He has been known to richly reward those who earn his trust and support his endeavors.",
{["ID"] = 1001,	["Name"] = "Bladespire Clan",							["External"] = "The Bladespire Clan",				["Display"] = 1,	["Info"] = "",
{["ID"] = 531,	["Name"] = "Dragonflight, Bronze",						["External"] = "The Bronze Dragonflight",			["Display"] = 1,	["Info"] = "",
{["ID"] = 910,	["Name"] = "Brood of Nozdormu",							["External"] = "The Brood of Nozdormu",				["Display"] = 1,	["Info"] = "The descendants of the Bronze Dragonflight are the guardians of time and care little for the mortal races.",
{["ID"] = 429,	["Name"] = "Burning Blade",								["External"] = "The Burning Blade",					["Display"] = 1,	["Info"] = "",
{["ID"] = 609,	["Name"] = "Cenarion Circle",							["External"] = "The Cenarion Circle",				["Display"] = 1,	["Info"] = "The druids of Cenarion Circle are guardians of nature and make their home in tranquil Moonglade.",
{["ID"] = 933,	["Name"] = "The Consortium",							["External"] = "The Consortium",					["Display"] = 1,	["Info"] = "Led by Nexus-Prince Haramad, the Consortium is a loosely affiliated cartel of ethereal smugglers, traders and thieves that has come to Outland to benefit from its riches.",
{["ID"] = 510,	["Name"] = "The Defilers",								["External"] = "The Defilers",						["Display"] = 1,	["Info"] = "The Defilers seek to claim Arathi Basin's valuable resources for the Horde.",
{["ID"] = 1135,	["Name"] = "The Earthen Ring",							["External"] = "The Earthen Ring",					["Display"] = 1,	["Info"] = "This gathering of the most powerful shaman of Azeroth seeks to maintain the balance between the world's elemental forces.  Their main focus during the cataclysm has been to  repair and stabilize the damage caused by Deathwing's arrival.",
{["ID"] = 1122,	["Name"] = "Earthen",									["External"] = "The Earthen",						["Display"] = 1,	["Info"] = "",
{["ID"] = 68,	["Name"] = "Undercity",									["External"] = "The Forsaken",						["Display"] = 1,	["Info"] = "Led by Sylvanas Windrunner, the Forsaken have joined a tenuous alliance with the Horde and established this capital in the vast depths under the Ruins of Lordaeron.",
{["ID"] = 1269,	["Name"] = "Golden Lotus",								["External"] = "The Golden Lotus",					["Display"] = 1,	["Info"] = "This mysterious society of Pandaren intend to solve the Mogu problem once and for all.",
{["ID"] = 44,	["Name"] = "Dragonflight, Green",						["External"] = "The Green Dragonflight",			["Display"] = 1,	["Info"] = "",
{["ID"] = 1067,	["Name"] = "The Hand of Vengeance",						["External"] = "The Hand of Vengeance",				["Display"] = 1,	["Info"] = "The Forsaken tasked by Sylvanas Windrunner with enacting Undercity's vengeance against Arthas by delivering the latest strain of their deadly Plague.",
{["ID"] = 67,	["Name"] = "Horde",										["External"] = "The Horde",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1947,	["Name"] = "Illidari",									["External"] = "The Illidari",						["Display"] = 1,	["Info"] = "Elves that have sworn themselves to fighting against the Burning Legion, no matter the cost.",
{["ID"] = 1120,	["Name"] = "Iron Giants",								["External"] = "The Iron Giants",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1623,	["Name"] = "The Iron Horde",							["External"] = "The Iron Horde",					["Display"] = 1,	["Info"] = "A tenuous alliance of many of the orc clans of Draenor under the leadership of Grommash Hellscream.",
{["ID"] = 1073,	["Name"] = "The Kalu'ak",								["External"] = "The Kalu'ak",						["Display"] = 1,	["Info"] = "The tuskarr are a tough but peaceful people who derive their livelihood from fishing and whaling.  Their settlements have recently come under fierce attack and welcome any allies who would come to their aid.",
{["ID"] = 989,	["Name"] = "Keepers of Time",							["External"] = "The Keepers of Time",				["Display"] = 1,	["Info"] = "The Keepers of Time are bronze dragons hand-picked by Nozdormu to watch over the Caverns of Time.",
{["ID"] = 1387,	["Name"] = "Kirin Tor Offensive",						["External"] = "The Kirin Tor Offensive",			["Display"] = 1,	["Info"] = "Ignited by Jaina's fury, the Kirin Tor Offensive seek to seize Thunder Isle for the glory of the Alliance!",
{["ID"] = 1090,	["Name"] = "Kirin Tor",									["External"] = "The Kirin Tor",						["Display"] = 1,	["Info"] = "The mages and archmages running the city of Dalaran.  Faced with the rising threats of the Blue Dragonflight and the Scourge, they've transported their city to the heart of Northrend.",
{["ID"] = 1337,	["Name"] = "The Klaxxi",								["External"] = "The Klaxxi",						["Display"] = 1,	["Info"] = "These Mantid Elders are untouched by the corruption and insanity that has overtaken the remainder of the Mantid Swarm. They seek to work with the races of Pandaria to restore their Queen to glory.",
{["ID"] = 509,	["Name"] = "The League of Arathor",						["External"] = "The League of Arathor",				["Display"] = 1,	["Info"] = "The League of Arathor seeks to reclaim the lost land of Arathi Basin for their benefactors in Stormwind.",
{["ID"] = 1345,	["Name"] = "The Lorewalkers",							["External"] = "The Lorewalkers",					["Display"] = 1,	["Info"] = "Caretakers of the mysteries of Pandaria, these brave souls roam the continent, hoping to learn from their history.",
{["ID"] = 941,	["Name"] = "The Mag'har",								["External"] = "The Mag'har Clan",					["Display"] = 1,	["Info"] = "This reclusive group of brown-skinned orcs has escaped any form of demonic corruption.  They have retained their traditional way of life in the face of great changes in Outland.",
{["ID"] = 1336,	["Name"] = "The Mantid Swarm",							["External"] = "The Mantid Swarm",					["Display"] = 1,	["Info"] = "The ravening swarms of the Mantid roam the Towlong Steppes and Dread Wastes, crushing all in their path.",
{["ID"] = 1268,	["Name"] = "Mogu",										["External"] = "The Mogu",							["Display"] = 1,	["Info"] = "The ancient progenitors of this land, the Mogu hate any and all pretenders, including the upstart Pandaren.",
{["ID"] = 1989,	["Name"] = "Moon Guard",								["External"] = "The Moon Guard",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1015,	["Name"] = "Netherwing",								["External"] = "The Netherwing",					["Display"] = 1,	["Info"] = "This unusual brood of dragons was spawned from the eggs of Deathwing's black dragonflight, and infused with raw nether-energies.  Now, they seek to find their identity beyond the shadows of their father's destructive heritage.",
{["ID"] = 49,	["Name"] = "Human, Night Watch",						["External"] = "The Night's Watch",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1913,	["Name"] = "Nightborne",								["External"] = "The Nightborne",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1859,	["Name"] = "The Nightfallen",							["External"] = "The Nightfallen",					["Display"] = 1,	["Info"] = "These exiled Nightborne elves suffer withdrawals after being cut off from the Nightwell. They oppose their people's alliance with the Legion and fight for some kind of redemption.",
{["ID"] = 1105,	["Name"] = "The Oracles",								["External"] = "The Oracles",						["Display"] = 1,	["Info"] = "The gorlocs of Sholazar Basin are a race of reptilian creatures who see themselves as guardians of the titan technology that remains in the zone (though they understand little of it).  They find themselves in an escalating territorial war with the wolvar.",
{["ID"] = 1509,	["Name"] = "The Pale",									["External"] = "The Pale",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1003,	["Name"] = "Protectorate",								["External"] = "The Protectorate",					["Display"] = 1,	["Info"] = "",
{["ID"] = 50,	["Name"] = "Dragonflight, Red",							["External"] = "The Red Dragonflight",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1850,	["Name"] = "The Saberstalkers",							["External"] = "The Saberstalkers",					["Display"] = 1,	["Info"] = "The treacherous wilds of Tanaan Jungle have attracted the craftiest hunters from both Azeroth and Draenor. To defeat the beasts of Tanaan, one must become a beast.",
{["ID"] = 1665,	["Name"] = "The Sargerei",								["External"] = "The Sargerei",						["Display"] = 1,	["Info"] = "Twisted in the service of the Shadow Council, these draenei have sacrificed much in pursuit of power.",
{["ID"] = 990,	["Name"] = "The Scale of the Sands",					["External"] = "The Scale of the Sands",			["Display"] = 1,	["Info"] = "A secretive subgroup of the Bronze Dragonflight, led by Soridormi, prime mate of Nozdormu.",
{["ID"] = 56,	["Name"] = "Scarlet Crusade",							["External"] = "The Scarlet Crusade",				["Display"] = 1,	["Info"] = "",
{["ID"] = 934,	["Name"] = "The Scryers",								["External"] = "The Scryers",						["Display"] = 1,	["Info"] = "Voren'thal the Seer leads the dissident blood elves who've rejected Kael'thas' path to power.  They've joined forces with the naaru of Shattrath City, much to the dismay of the Aldor.",
{["ID"] = 1252,	["Name"] = "Sha",										["External"] = "The Sha",							["Display"] = 1,	["Info"] = "The evil spirits of the land.",
{["ID"] = 935,	["Name"] = "The Sha'tar",								["External"] = "The Sha'tar",						["Display"] = 1,	["Info"] = "The Sha'tar are a group of powerful naaru who rule over a rebuilt Shattrath City.  With the help of the Aldor and the Scryers, they lead the battle against Illidan and the Burning Legion.",
{["ID"] = 1270,	["Name"] = "Shado-Pan",									["External"] = "The Shado-Pan",						["Display"] = 1,	["Info"] = "The shadowy protectors of Pandaria's temples, the Shado-Pan are wrought with mystery.",
{["ID"] = 1521,	["Name"] = "Shadow Council",							["External"] = "The Shadow Council",				["Display"] = 1,	["Info"] = "",
{["ID"] = 1094,	["Name"] = "The Silver Covenant",						["External"] = "The Silver Covenant",				["Display"] = 1,	["Info"] = "A militant core of high elves that rejects the admission of blood elves into the Kirin Tor.  They've united under the banner of Vereesa Windrunner and joined the Alliance forces in Northrend.",
{["ID"] = 1119,	["Name"] = "The Sons of Hodir",							["External"] = "The Sons of Hodir",					["Display"] = 1,	["Info"] = "The frost giants of the Storm Peaks are a war-like race that makes their home in Dun Niffelem.",
{["ID"] = 940,	["Name"] = "The Sons of Lothar",						["External"] = "The Sons of Lothar",				["Display"] = 1,	["Info"] = "",
{["ID"] = 968,	["Name"] = "Sunhawks",									["External"] = "The Sunhawks",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1124,	["Name"] = "The Sunreavers",							["External"] = "The Sunreavers",					["Display"] = 1,	["Info"] = "Traditionally barred from Dalaran, the Horde has been accepted into the city through the efforts of Archmage Aethas Sunreaver.  His followers have taken up his name and watch over the ward known as Sunreaver's Sanctuary.",
{["ID"] = 1064,	["Name"] = "The Taunka",								["External"] = "The Taunka",						["Display"] = 1,	["Info"] = "These hardy people are cousins of the Tauren and have become valuable scouts for the armies of the Horde as they march northward.",
{["ID"] = 1272,	["Name"] = "The Tillers",								["External"] = "The Tillers",						["Display"] = 1,	["Info"] = "The Tillers are peaceful and productive pandaren, working with the land to feed the massive appetites of their people.",
{["ID"] = 1491,	["Name"] = "The Timewalkers",							["External"] = "The Timewalkers",					["Display"] = 1,	["Info"] = "The Timewalkers guard the timeways from those who would take advantage of the bronze dragonflight's mortality; most are adventurers or scholars that have previously worked with the Keepers of Time.",
{["ID"] = 311,	["Name"] = "Titan",										["External"] = "The Titans",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1047,	["Name"] = "Tuskarr",									["External"] = "The Tuskarr",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1128,	["Name"] = "Twilight's Hammer",							["External"] = "The Twilight's Hammer",				["Display"] = 1,	["Info"] = "",
{["ID"] = 967,	["Name"] = "The Violet Eye",							["External"] = "The Violet Eye",					["Display"] = 1,	["Info"] = "A secret sect of the Kirin Tor founded to spy on Medivh and his activities.",
{["ID"] = 1045,	["Name"] = "Vrykul",									["External"] = "The Vrykul",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1894,	["Name"] = "The Wardens",								["External"] = "The Wardens",						["Display"] = 1,	["Info"] = "After Legion forces broke the Vault of the Wardens with the aid of Gul'dan, what few Wardens remain are determined to rebuild their prison and hunt down the terrifying beasts that were let loose when it fell.",
{["ID"] = 1016,	["Name"] = "Wyrmcult",									["External"] = "The Wyrmcult",						["Display"] = 1,	["Info"] = "",
{["ID"] = 1091,	["Name"] = "The Wyrmrest Accord",						["External"] = "The Wyrmrest Accord",				["Display"] = 1,	["Info"] = "With the Blue Dragonflight's violent upheaval against all mortal users of magic, the remaining dragonflights have banded under the leadership of the Red Dragonflight to combat their wayward kin.",
{["ID"] = 108,	["Name"] = "Theramore",									["External"] = "Theramore",							["Display"] = 1,	["Info"] = "",
{["ID"] = 1171,	["Name"] = "Therazane",									["External"] = "Therazane",							["Display"] = 1,	["Info"] = "The elemental plane of earth, Deepholm, is ruled by Therazane and her children, the Stone Lords.  After witnessing the devastation Deathwing and his followers caused her realm, Therazane treats all outsiders with open hostility.",
{["ID"] = 59,	["Name"] = "Thorium Brotherhood",						["External"] = "Thorium Brotherhood",				["Display"] = 1,	["Info"] = "The dwarves of the Thorium Brotherhood epitomize excellence in craftsmanship and are bent on unlocking the secrets of Blackrock Mountain.",
{["ID"] = 947,	["Name"] = "Thrallmar",									["External"] = "Thrallmar",							["Display"] = 1,	["Info"] = "The expedition sent through the Dark Portal by Thrall has built a stronghold in Hellfire Peninsula.  Thrallmar serves as a base of operations for much of the Horde's activities in Outland.",
{["ID"] = 576,	["Name"] = "Timbermaw Hold",							["External"] = "Timbermaw Hold",					["Display"] = 1,	["Info"] = "As the last uncorrupted furbolg tribe, the Timbermaw seek to preserve their spiritual ways and end the suffering of their brethren.",
{["ID"] = 922,	["Name"] = "Tranquillien",								["External"] = "Tranquillien",						["Display"] = 1,	["Info"] = "Once a high elf town, Tranquillien became abandoned after the Scourge invaded Quel'Thalas.  It has now been reclaimed by the Forsaken and the blood elves who seek to rid the Ghostlands of the Scourge.",
{["ID"] = 1948,	["Name"] = "Valarjar",									["External"] = "Valarjar Vryukul",					["Display"] = 1,	["Info"] = "These are the chosen warriors of Odyn, sworn to his service in life and death.",
{["ID"] = 1050,	["Name"] = "Valiance Expedition",						["External"] = "Valiance Expedition",				["Display"] = 1,	["Info"] = "The main armies of the Alliance in Northrend, moving against the Scourge and unified under King Varian Wrynn's command.",
{["ID"] = 41,	["Name"] = "Venture Company",							["External"] = "Venture Co.",						["Display"] = 1,	["Info"] = "",
{["ID"] = 572,	["Name"] = "Troll, Vilebranch",							["External"] = "Vilebranch Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1848,	["Name"] = "Vol'jin's Headhunters",						["External"] = "Vol'jin's Headhunters",				["Display"] = 1,	["Info"] = "Seeking to protect Azeroth with a decisive victory on Draenor, Warchief Vol'jin is assembling an elite team of champions to establish a foothold in Tanaan Jungle and to overthrow Gul'dan.",
{["ID"] = 1085,	["Name"] = "Warsong Offensive",							["External"] = "Warsong Offensive",					["Display"] = 1,	["Info"] = "Garrosh Hellscream commands the Horde's main expeditionary forces as they make their way into Northrend to face Arthas and the armies of the Scourge.",
{["ID"] = 889,	["Name"] = "Warsong Outriders",							["External"] = "Warsong Outriders",					["Display"] = 1,	["Info"] = "Fierce orcs of the Warsong Clan, locked in battle against the Silverwing Sentinels in Warsong Gulch.",
{["ID"] = 1174,	["Name"] = "Wildhammer Clan",							["External"] = "Wildhammer Dwarves",				["Display"] = 1,	["Info"] = "The Wildhammer dwarves are known for their near-reckless courage as well as their unsurpassed gryphon-riding skills.  After losing their home of Grim Batol to a Dark Iron Curse, they've spread their dwellings around the Twilight Highlands.",
{["ID"] = 1079,	["Name"] = "Murloc, Winterfin",							["External"] = "Winterfin Murlocs",					["Display"] = 1,	["Info"] = "",
{["ID"] = 82,	["Name"] = "Troll, Witherbark",							["External"] = "Witherbark Trolls",					["Display"] = 1,	["Info"] = "",
{["ID"] = 1153,	["Name"] = "PLAYER, Worgen",							["External"] = "Worgen",							["Display"] = 1,	["Info"] = "",
{["ID"] = 270,	["Name"] = "Zandalar Tribe",							["External"] = "Zalandar Trolls",					["Display"] = 1,	["Info"] = "These trolls have come to Yojamba Isle in an effort to recruit help against the resurrected Blood God and his Atal'ai Priests in Zul'Gurub.",
{["ID"] = 189,	["Name"] = "Alliance Generic",							["External"] = "Alliance",							["Display"] = 0,	["Info"] = "",
{["ID"] = 148,	["Name"] = "Ambient",									["External"] = "Ambient",							["Display"] = 0,	["Info"] = "",
{["ID"] = 689,	["Name"] = "Dragonflight, Black - Bait",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 914,	["Name"] = "PLAYER, Blood Elf",							["External"] = "Blood Elf",							["Display"] = 0,	["Info"] = "",
{["ID"] = 709,	["Name"] = "Battleground Neutral",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 43,	["Name"] = "Basilisk",									["External"] = "Basilisks",							["Display"] = 0,	["Info"] = "",
{["ID"] = 310,	["Name"] = "Beast - Bat",								["External"] = "Bat",								["Display"] = 0,	["Info"] = "",
{["ID"] = 37,	["Name"] = "Beast - Bear",								["External"] = "Bears",								["Display"] = 0,	["Info"] = "",
{["ID"] = 88,	["Name"] = "Blackfathom",								["External"] = "Blackthom",							["Display"] = 0,	["Info"] = "",
{["ID"] = 23,	["Name"] = "Beast - Boar",								["External"] = "Boars",								["Display"] = 0,	["Info"] = "",
{["ID"] = 669,	["Name"] = "Beast - Carrion Bird",						["External"] = "Carrion Bird",						["Display"] = 0,	["Info"] = "",
{["ID"] = 7,	["Name"] = "Creature",									["External"] = "Creature",							["Display"] = 0,	["Info"] = "",
{["ID"] = 489,	["Name"] = "Goblin, Dark Iron Bar Patron",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 63,	["Name"] = "Darkhowl",									["External"] = "Darkhowl",							["Display"] = 0,	["Info"] = "",
{["ID"] = 9,	["Name"] = "PLAYER, Troll",								["External"] = "Darkspear",							["Display"] = 0,	["Info"] = "",
{["ID"] = 73,	["Name"] = "Demon",										["External"] = "Demon",								["Display"] = 0,	["Info"] = "",
{["ID"] = 927,	["Name"] = "PLAYER, Draenei",							["External"] = "Draenei",							["Display"] = 0,	["Info"] = "",
{["ID"] = 3,	["Name"] = "PLAYER, Dwarf",								["External"] = "Dwarf",								["Display"] = 0,	["Info"] = "",
{["ID"] = 74,	["Name"] = "Elemental",									["External"] = "Elemental",							["Display"] = 0,	["Info"] = "",
{["ID"] = 128,	["Name"] = "Enemy",										["External"] = "Enemy",								["Display"] = 0,	["Info"] = "",
{["ID"] = 40,	["Name"] = "Escortee",									["External"] = "Escortees",							["Display"] = 0,	["Info"] = "",
{["ID"] = 62,	["Name"] = "Forlorn Spirit",							["External"] = "Forlorn Spirits",					["Display"] = 0,	["Info"] = "",
{["ID"] = 5,	["Name"] = "PLAYER, Undead",							["External"] = "Forsaken",							["Display"] = 0,	["Info"] = "",
{["ID"] = 31,	["Name"] = "Friendly",									["External"] = "Friendly",							["Display"] = 0,	["Info"] = "",
{["ID"] = 65,	["Name"] = "Furbolg",									["External"] = "Furbolg",							["Display"] = 0,	["Info"] = "",
{["ID"] = 511,	["Name"] = "Giant",										["External"] = "Giant -",							["Display"] = 0,	["Info"] = "",
{["ID"] = 8,	["Name"] = "PLAYER, Gnome",								["External"] = "Gnome",								["Display"] = 0,	["Info"] = "",
{["ID"] = 389,	["Name"] = "Gnomeregan Bug",							["External"] = "Gnomer -",							["Display"] = 0,	["Info"] = "",
{["ID"] = 1152,	["Name"] = "PLAYER, Goblin",							["External"] = "Goblin",							["Display"] = 0,	["Info"] = "",
{["ID"] = 58,	["Name"] = "Beast - Gorilla",							["External"] = "Gorillas",							["Display"] = 0,	["Info"] = "",
{["ID"] = 64,	["Name"] = "Grell",										["External"] = "Grell",								["Display"] = 0,	["Info"] = "",
{["ID"] = 66,	["Name"] = "Horde Generic",								["External"] = "Horde",								["Display"] = 0,	["Info"] = "",
{["ID"] = 1,	["Name"] = "PLAYER, Human",								["External"] = "Human",								["Display"] = 0,	["Info"] = "",
{["ID"] = 1000,	["Name"] = "Khadgar's Servant",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1002,	["Name"] = "Ethereum Sparbuddy",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1004,	["Name"] = "Arcane Annihilator (DNR)",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1006,	["Name"] = "Kirin'Var - Dathric",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1007,	["Name"] = "Kirin'Var - Belmara",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1008,	["Name"] = "Kirin'Var - Luminrath",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1009,	["Name"] = "Kirin'Var - Cohlien",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1010,	["Name"] = "Servant of Illidan",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1013,	["Name"] = "Spirits of Shadowmoon 1",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1014,	["Name"] = "Spirits of Shadowmoon 2",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1017,	["Name"] = "Treant",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1018,	["Name"] = "Leotheras Demon I",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1019,	["Name"] = "Leotheras Demon II",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1020,	["Name"] = "Leotheras Demon III",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1021,	["Name"] = "Leotheras Demon IV",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1022,	["Name"] = "Leotheras Demon V",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1023,	["Name"] = "Azaloth",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1025,	["Name"] = "Flayer Hunter",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1026,	["Name"] = "Shadowmoon Shade",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1027,	["Name"] = "Legion Communicator",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1029,	["Name"] = "Chess, Friendly to All Chess",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1033,	["Name"] = "Maiev",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1034,	["Name"] = "Skettis Shadowy Arakkoa",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1035,	["Name"] = "Skettis Arakkoa",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1036,	["Name"] = "Dragonmaw Enemy",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1041,	["Name"] = "Frenzy",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1042,	["Name"] = "Skyguard Enemy",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1044,	["Name"] = "Theramore Deserter",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1046,	["Name"] = "Northsea Pirates",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1048,	["Name"] = "UNUSED",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1054,	["Name"] = "Spotted Gryphon",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1055,	["Name"] = "Tamed Plaguehound",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1056,	["Name"] = "Vrykul (Ancient Spirit 1)",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1057,	["Name"] = "Vrykul (Ancient Siprit 2)",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1058,	["Name"] = "Vrykul (Ancient Siprit 3)",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1059,	["Name"] = "CTF - Flag - Alliance",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1060,	["Name"] = "Test",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1062,	["Name"] = "Vrykul Gladiator",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1063,	["Name"] = "Valgarde Combatant",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1065,	["Name"] = "Monster, Zone Force Reaction 1",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1066,	["Name"] = "Monster, Zone Force Reaction 2",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1069,	["Name"] = "Ram Racing Powerup DND",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1070,	["Name"] = "Ram Racing Trap DND",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1071,	["Name"] = "Craig's Squirrels",							["External"] = "",									["Display"] = 0,	["Info"] = "A test faction.",
{["ID"] = 1074,	["Name"] = "Holiday - Water Barrel",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1078,	["Name"] = "Fighting Vanity Pet",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1080,	["Name"] = "Friendly, Force Reaction 1",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1081,	["Name"] = "Object, Force Reaction",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1086,	["Name"] = "Poacher",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1087,	["Name"] = "Holiday Monster",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1092,	["Name"] = "Azjol-Nerub",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1095,	["Name"] = "Grizzly Hills Trapper",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1099,	["Name"] = "Wrathgate Scourge",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1100,	["Name"] = "Wrathgate Alliance",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1101,	["Name"] = "Wrathgate Horde",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1102,	["Name"] = "CTF - Flag - Horde",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1103,	["Name"] = "CTF - Flag - Neutral",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1108,	["Name"] = "CoT Arthas",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1109,	["Name"] = "CoT Stratholme Citizen",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1110,	["Name"] = "CoT Scourge",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1111,	["Name"] = "Freya",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1112,	["Name"] = "Mount - Taxi - Alliance",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1113,	["Name"] = "Mount - Taxi - Horde",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1114,	["Name"] = "Mount - Taxi - Neutral",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1115,	["Name"] = "Elemental, Water",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1116,	["Name"] = "Elemental, Air",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1123,	["Name"] = "Monster Referee",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1125,	["Name"] = "Hyldsmeet",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1130,	["Name"] = "Stag, Darkshore",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1131,	["Name"] = "Bear, Darkshore",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1132,	["Name"] = "Moonstalker, Darkshore",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1138,	["Name"] = "Cataclysm - New Neutral Reputation",		["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1142,	["Name"] = "Magram Remnant",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1143,	["Name"] = "Sons of Gelkis",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1144,	["Name"] = "REUSE",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1145,	["Name"] = "Hates Everything",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1157,	["Name"] = "Pygmy",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1159,	["Name"] = "CTF - Flag - Alliance 2",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1160,	["Name"] = "CTF - Flag - Horde 2",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1179,	["Name"] = "Slime",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1181,	["Name"] = "Friendly, New",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1233,	["Name"] = "CoT Well of Eternity - Illidan",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1234,	["Name"] = "CoT Well of Eternity - High Elves",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1235,	["Name"] = "CoT Well of Eternity - Illidan (Stealth)",	["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1237,	["Name"] = "CoT Well of Eternity - Demons",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1240,	["Name"] = "CoT Well of Eternity - Demon Balls",		["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1241,	["Name"] = "CoT Well of Eternity - Hunter Stalkers",	["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1249,	["Name"] = "PLAYER, Expansion 4 Neutral",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1253,	["Name"] = "Guardians of the East Temple",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1286,	["Name"] = "Guardians of the Red Crane",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1338,	["Name"] = "Gurthan Mogu",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1339,	["Name"] = "Harthak Mogu",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1340,	["Name"] = "Korgesh Mogu",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1364,	["Name"] = "Friendly, Force Reaction 2",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1366,	["Name"] = "Friendly, Force Reaction 3",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1367,	["Name"] = "Friendly, Force Reaction 4",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1368,	["Name"] = "Friendly, Force Reaction 5",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1369,	["Name"] = "Friendly, Force Reaction 6",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1370,	["Name"] = "Friendly, Force Reaction 7",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1433,	["Name"] = "Monster, Enforced Neutral For Force ", 		["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1457,	["Name"] = "Forelings",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1483,	["Name"] = "Foreling-Eaters",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1500,	["Name"] = "Red Phantom",								["External"] = "",									["Display"] = 0,	["Info"] = "You've been corrupted by the power of Ordos, and have turned against your friends and foes in mindless rage.",
{["ID"] = 1591,	["Name"] = "Draenei, Draenor",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1617,	["Name"] = "Primal",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1618,	["Name"] = "Breaker",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1674,	["Name"] = "Draenor Spores",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1687,	["Name"] = "Gorgrond Goren",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1746,	["Name"] = "Nagrand Gronn",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1747,	["Name"] = "Coliseum Treasure",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1756,	["Name"] = "LVA_Looters",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1757,	["Name"] = "LVA_Preservers",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1758,	["Name"] = "LVA_Naturalists",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1759,	["Name"] = "LVA_Machines",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1760,	["Name"] = "Highmaul Gladiators",						["External"] = "",									["Display"] = 0,	["Info"] = "Highmaul ogres like togas and gladiator fights.",
{["ID"] = 1786,	["Name"] = "Burning Legion Invaders",					["External"] = "",									["Display"] = 0,	["Info"] = "Demons from places unknown and unrivaled in power.",
{["ID"] = 1815,	["Name"] = "Gilnean Survivors",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1833,	["Name"] = "Uncrowned",									["External"] = "",									["Display"] = 0,	["Info"] = "If you have to ask, you're already dead.",
{["ID"] = 1905,	["Name"] = "Dreamgrove Druid",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1911,	["Name"] = "Kvaldir Ghosts",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1914,	["Name"] = "Withered",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1920,	["Name"] = "Moon Guard",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1953,	["Name"] = "Nightmare",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 1962,	["Name"] = "Nightborne Civilian",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 769,	["Name"] = "Gizlock's Dummy",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 770,	["Name"] = "Gizlock's Charm",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 771,	["Name"] = "Gizlock",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 790,	["Name"] = "Spirit Guide - Alliance",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 829,	["Name"] = "Ogre (Captain Kromcrush)",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 849,	["Name"] = "Spirit Guide - Horde",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 915,	["Name"] = "Armies of C'Thun",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 916,	["Name"] = "Silithid Attackers",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 918,	["Name"] = "RC Enemies",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 919,	["Name"] = "RC Objects",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 920,	["Name"] = "Red",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 921,	["Name"] = "Blue",										["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 928,	["Name"] = "Scourge Invaders",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 931,	["Name"] = "Test Faction (not a real faction)",			["External"] = "",									["Display"] = 0,	["Info"] = "This faction only exists to test the editing of faction names and descriptions...",
{["ID"] = 944,	["Name"] = "Fel Orc Ghost",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 945,	["Name"] = "Sons of Lothar Ghosts",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 949,	["Name"] = "Test Faction 1",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 950,	["Name"] = "ToWoW - Flag",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 951,	["Name"] = "ToWoW - Flag Trigger Alliance (DND)",		["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 952,	["Name"] = "Test Faction 3",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 953,	["Name"] = "Test Faction 4",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 954,	["Name"] = "ToWoW - Flag Trigger Horde (DND)",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 957,	["Name"] = "Earth Elemental",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 958,	["Name"] = "Fighting Robots",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 959,	["Name"] = "Actor Good",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 960,	["Name"] = "Actor Evil",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 962,	["Name"] = "Crazed Owlkin",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 963,	["Name"] = "Chess Alliance",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 964,	["Name"] = "Chess Horde",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 965,	["Name"] = "Monster Spar",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 966,	["Name"] = "Monster Spar Buddy",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 971,	["Name"] = "Fungal Giant",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 973,	["Name"] = "Monster, Predator",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 974,	["Name"] = "Monster, Prey",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 975,	["Name"] = "Void Anomaly",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 976,	["Name"] = "Hyjal Defenders",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 977,	["Name"] = "Hyjal Invaders",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 981,	["Name"] = "Arakkoa",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 982,	["Name"] = "Zangarmarsh Banner (Alliance)",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 983,	["Name"] = "Zangarmarsh Banner (Horde)",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 984,	["Name"] = "Zangarmarsh Banner (Neutral)",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 985,	["Name"] = "Caverns of Time - Thrall",					["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 986,	["Name"] = "Caverns of Time - Durnholde",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 987,	["Name"] = "Caverns of Time - Southshore Guards",		["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 988,	["Name"] = "Shadow Council Covert",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 991,	["Name"] = "Dark Portal Defender, Alliance",			["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 992,	["Name"] = "Dark Portal Defender, Horde",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 993,	["Name"] = "Dark Portal Attacker, Legion",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 994,	["Name"] = "Inciter Trigger",							["External"] = "",									["Display"] = 0,	["Info"] = "Used for the Blackheart the Inciter event.",
{["ID"] = 995,	["Name"] = "Inciter Trigger 2",							["External"] = "",									["Display"] = 0,	["Info"] = "Used for the Blackheart the Inciter event.",
{["ID"] = 996,	["Name"] = "Inciter Trigger 3",							["External"] = "",									["Display"] = 0,	["Info"] = "Used for the Blackheart the Inciter event.",
{["ID"] = 997,	["Name"] = "Inciter Trigger 4",							["External"] = "",									["Display"] = 0,	["Info"] = "Used for the Blackheart the Inciter event.",
{["ID"] = 998,	["Name"] = "Inciter Trigger 5",							["External"] = "",									["Display"] = 0,	["Info"] = "Used for the Blackheart the Inciter event.",
{["ID"] = 999,	["Name"] = "Mana Creature",								["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 25,	["Name"] = "Kobold",									["External"] = "Kobolds",							["Display"] = 0,	["Info"] = "",
{["ID"] = 55,	["Name"] = "Leopard",									["External"] = "Leorpards",							["Display"] = 0,	["Info"] = "",
{["ID"] = 89,	["Name"] = "Makrura",									["External"] = "Makrura",							["Display"] = 0,	["Info"] = "",
{["ID"] = 14,	["Name"] = "Monster",									["External"] = "Monster",							["Display"] = 0,	["Info"] = "",
{["ID"] = 19,	["Name"] = "Murloc",									["External"] = "Murlocs",							["Display"] = 0,	["Info"] = "",
{["ID"] = 168,	["Name"] = "Nethergarde Caravan",						["External"] = "Nethergarde Caravan",				["Display"] = 0,	["Info"] = "",
{["ID"] = 4,	["Name"] = "PLAYER, Night Elf",							["External"] = "Night Elf",							["Display"] = 0,	["Info"] = "",
{["ID"] = 38,	["Name"] = "Ogre",										["External"] = "Ogres",								["Display"] = 0,	["Info"] = "",
{["ID"] = 2,	["Name"] = "PLAYER, Orc",								["External"] = "Orc",								["Display"] = 0,	["Info"] = "",
{["ID"] = 28,	["Name"] = "Prey",										["External"] = "Prey",								["Display"] = 0,	["Info"] = "",
{["ID"] = 42,	["Name"] = "Beast - Raptor",							["External"] = "Raptors",							["Display"] = 0,	["Info"] = "",
{["ID"] = 110,	["Name"] = "Quilboar, Razormane 2",						["External"] = "Razorfen Quillboar",				["Display"] = 0,	["Info"] = "",
{["ID"] = 1024,	["Name"] = "Rock Flayer",								["External"] = "Rock Flayer",						["Display"] = 0,	["Info"] = "",
{["ID"] = 309,	["Name"] = "Scorpid",									["External"] = "Scorpid",							["Display"] = 0,	["Info"] = "",
{["ID"] = 20,	["Name"] = "Undead, Scourge",							["External"] = "Scourge",							["Display"] = 0,	["Info"] = "",
{["ID"] = 450,	["Name"] = "Searing Spider",							["External"] = "Searing Spider",					["Display"] = 0,	["Info"] = "",
{["ID"] = 449,	["Name"] = "Shadowsilk Poacher",						["External"] = "Shadowsilk Poacher",				["Display"] = 0,	["Info"] = "",
{["ID"] = 269,	["Name"] = "Silvermoon Remnant",						["External"] = "Silvermoon Remnant",				["Display"] = 0,	["Info"] = "",
{["ID"] = 79,	["Name"] = "HIllsbrad, Southshore Mayor",				["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 22,	["Name"] = "Beast - Spider",							["External"] = "Spiders",							["Display"] = 0,	["Info"] = "",
{["ID"] = 75,	["Name"] = "Spirit",									["External"] = "Spirit",							["Display"] = 0,	["Info"] = "",
{["ID"] = 329,	["Name"] = "Taskmaster Fizzule",						["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 6,	["Name"] = "PLAYER, Tauren ",							["External"] = "Tauren",							["Display"] = 0,	["Info"] = "",
{["ID"] = 679,	["Name"] = "Training Dummy",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 77,	["Name"] = "Treasure",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 32,	["Name"] = "Trogg",										["External"] = "Troggs",							["Display"] = 0,	["Info"] = "",
{["ID"] = 575,	["Name"] = "Furbolg, Uncorrupted",						["External"] = "Uncorrupted Furbolg",				["Display"] = 0,	["Info"] = "",
{["ID"] = 36,	["Name"] = "Victim",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 35,	["Name"] = "Villian",									["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 229,	["Name"] = "Wailing Caverns",							["External"] = "",									["Display"] = 0,	["Info"] = "",
{["ID"] = 589,	["Name"] = "Wintersaber Trainers",						["External"] = "Wintersaber Trainers",				["Display"] = 0,	["Info"] = "This small group of reclusive night elves raises and trains wintersabers in the Winterspring area.",
{["ID"] = 29,	["Name"] = "Beast - Wolf",								["External"] = "Wolves",							["Display"] = 0,	["Info"] = "",
{["ID"] = 24,	["Name"] = "Worgen",									["External"] = "Worgen",							["Display"] = 0,	["Info"] = "",