--
--	 Localization esES & esMX
--
-- HTML and colors need to be included in their translations.
-- \n is used for new lines
-- ["Variable"] =					<Translate here>	-- Origional english text

["S_AREA_NOLORE"] =	<<HTML><BODY><BR/><P align=\"CENTER\">No se conoce mucho sobre esta zona.</P></BODY></HTML>>					-- "<HTML><BODY><BR/><P align=\"CENTER\">Not much is known about this area.</P></BODY></HTML>"
["S_CONTINENT_DRAENOR"] =	<Draenor>			-- "Draenor"
["S_CONTINENT_EK"] =	<Reinos del Este>				-- "Eastern Kingdoms"
["S_CONTINENT_KALIMDOR"] =	<Kalimdor>			-- "Kalimdor"
["S_CONTINENT_NORTHREND"] =	<Rasganorte>			-- "Northrend"
["S_CONTINENT_OUTLAND"] =	<Terrallende>			-- "Outland"
["S_CONTINENT_PANDARIA"] =	<Pandaria>			-- "Pandaria"
["S_DAILY_SUGGESTIONS"] = <Sugerencias diarias>				-- "Daily Suggestions"
["S_ERROR_COMBATLOCKDOWN"] =	<No puedes abrir Lore Library en combate.>		-- "|cFFFF0000You can't open Lore Library while in combat.|r"
["S_LIBRARY_ADDED"] =	<Añadido a tu librería>				-- "Added to your library."
["S_LORE_COLLECTED"] =	<Lore obtenido>				-- "Lore collected"
["S_LORE_NOT_COLLECTED"] =	<Lore no obtenido>			-- "Lore not collected"
["S_LOSTPAGES_INFO"] =	<Puedes usar una página perdida\n para desbloquear este lore.>				-- "You can use a lost page\nto unlock this lore."
["S_LOSTPAGE_NONE"] = <No tienes páginas perdidas disponibles.>				-- "You have no lost pages available."
["S_LOSTPAGE_UNLOCK_INFO"] = <Puedes usar una página perdida\n para desbloquear este lore.>			-- "You can use a lost page\nto unlock this lore."
["S_LOSTPAGE_USE"] = <Usa una página perdida para desbloquear este lore.>					-- "Use a lost page to unlock this lore."
["S_LOST_PAGES"] =	<Páginas perdidas>					-- "Lost pages"
["S_MARK_WORLDMAP"] = <Marcar zona en el mapa del mundo>					-- "Mark area on the world map"
["S_MATCH_AREA"] = <Zonas descubiertas>						-- "Discovered areas"
["S_MATCH_ZONE"] = <Zonas>						-- "Zones"
["S_MINIMAPBUTTON_INFO"] =	<Pulsa para abrir tu librería.>			-- "Click to open your library."
["S_NEW"] =	<¡Nuevo!>							-- "New !"
["S_OPTIONS_MAPOPTIONS"] =	<Pins del mapa del mundo>			-- "World map pins"
["S_OPTIONS_MINIMAP"] =	<Botón del minimapa>				-- "Minimap button"
["S_OPTIONS_MOVEPOPUP"] =	<Mover popup>			-- "Move popup"
["S_OPTIONS_PINS_AREA"] =	<Zona>			-- "Area"
["S_OPTIONS_PINS_LORE"] =	<Documento>			-- "Document"
["S_OPTIONS_PINS_TOOLTIPS"] =	<Tooltips>		-- "Tooltips"
["S_OPTIONS_PINS_UNLOCKED"] =	<Desbloqueado>		-- "Unlocked"
["S_OPTIONS_POPUPOPTIONS"] =	<Popups>		-- "Popups"
["S_OPTIONS_TOOLTIP"] =	<Indicador de tooltip>				-- "Tooltip indicator"
["S_OPTIONS_WORLDMAP_OVERLAY"] =	<Cubrir mapa del mundo>	-- "World map overlay"
["S_PINS_OPTIONS_COLLECTED"] =	<Mostrar obtenidos>	-- "Show collected"
["S_PINS_OPTIONS_SHOW"] =	<Mostrar pins>			-- "Show pins"
["S_POI_BY_CONTINENT"] =	<Ordenar por continente>			-- "Sort by continent"
["S_POI_COMPLETED"] =	<Completado>				-- "Completed"
["S_POI_NOT_COMPLETED"] =	<No completado>			-- "Not completed"
["S_RIGHTCLICK_HIDE"] =	<Click derecho para ocultar.>				-- "Right click to hide."
["S_SOURCEINFO_CHEST"] =	<Encontrado en un tipo de cofre.>			-- "Found in a type of chest."
["S_SOURCEINFO_CONTAINER"] =	<Se puede encontrar en un contenedor.>		-- "Can be found in a container."
["S_SOURCEINFO_NPC"] =	<Puede ser obtenido en un botín.>				-- "Can drop from an npc."
["S_SOURCEINFO_OBJECT"] =	<Objeto encontrado en una zona.>			-- "Object found in a zone."
["S_SOURCEINFO_QUEST"] =	<Obtenido en una misión.>			-- "Obtained during a quest."
["S_SOURCEINFO_STEALTH"] =	<Se puede robar de un PNJ.>			-- "Can pickpocket from an npc."
["S_SOURCEINFO_UNAVAILABLE"] =	<Ya no se puede obtener.>		-- "Can no longer be obtained."
["S_SOURCEINFO_VENDOR"] =	<Vendido por un PNJ.>			-- "Sold by a vendor."
["S_SOURCETYPE_CHEST"] =	<Cofre>			-- "Chest"
["S_SOURCETYPE_CONTAINER"] =	<Contenedor>		-- "Container"
["S_SOURCETYPE_NPC"] =	<Botín>				-- "Drop"
["S_SOURCETYPE_OBJECT"] =	<Objeto>			-- "Object"
["S_SOURCETYPE_QUEST"] =	<Misión>			-- "Quest"
["S_SOURCETYPE_STEALTH"] =	<Robar>			-- "Pickpocket"
["S_SOURCETYPE_UNAVAILABLE"] =	<No disponible>		-- "Unavailable"
["S_SOURCETYPE_VENDOR"] =	<Vendedor>			-- "Vendor"
["S_SOURCE_TITLE"] =	<HTML><BODY><BR/><P align=\"center\">Este lore puede obtenerse de:</P><BR/></BODY></HTML>				-- "<HTML><BODY><BR/><P align=\"center\">This lore can be obtained from:</P><BR/></BODY></HTML>"
["S_SUGGESTION_COMPLETE"] =	<Sugerencia completada>			-- "Suggestion completed"
["S_SUGGESTION_EMPTY1"] =	<¡Has obtenido mucho lore!>			-- "You have collected so much lore!"
["S_SUGGESTION_EMPTY2"] =	<No queda nada por sugerir.>			-- "There is nothing left to suggest."
["S_SUGGESTION_REMOVE"] =	<Elimina esta sugerencia para poder obtener otra.>			-- "Remove this suggestion to make room for a new one."
["S_TAB_LORE"] =	<Documentos>					-- "Documents"
["S_TAB_POI"] =	<Zonas>						-- "Areas"
["S_TITLE_AREA"] =	<Librería de zona>					-- "Area Library"
["S_TITLE_DOCUMENT"] = <Librería de documentos>					-- "Document Library"
["S_UNAVAILABLE_DETAIL"] = <Este lore ya no puede ser obtenido.>				-- "This lore no longer has any\n available sources."
["S_UNLOCK_UNTIL_NEXT"] =	<Desbloqueos hasta el siguiente:>			-- "Unlocks until next:"
["S_ZONE_COMPLETE"] =	<Zonas completadas>				-- "Zone completed"
["S_CONTINENTS"] =	<Continentes>					-- "Continents"
["S_TIME_DAYS"] =	<días>					-- "days"
["S_TIME_DAY"] =	<día>					-- "day"
["S_TIME_HOURS"] = <horas>						-- "hours"
["S_TIME_MINS"] = <minutos>						-- "minutes"
["S_TIME_MIN"] = <minuto>						-- "minute"

["F_LORE_CONTENT"] =	<Contenido del lore:\nPalabrass: %d \nPáginas: %d \nImágenes: %d>				-- "Lore content:\nWords: %d \nPages: %d \nImages: %d"
["F_LORE_UNLOCK"] = <Añadido a la librería: %s>				-- "Lore Library added: %s"
["F_LOSTPAGE_INFO"] =	<Las páginas se obtienen con cada %d partes de lore que obtengas, y se pueden usar para obtener lore no disponible.>			-- "Pages are gained with every %d pieces of lore you unlock, and can be used to unlock unavailable lore."
["F_PAGE"] =	<Página %d>						-- "Page %d"
["F_SUGGESTION_REMOVECOOLDOWN"] =	<Se puede eliminar en %s.>	-- "Can be removed in %s."
["F_SUGGESTION_UNTILNEW"] =	<Nueva sugerencia en %s.>			-- "New suggestion in %s."
