--
--	 Localization ruRU
--
-- HTML and colors need to be included in their translations.
-- \n is used for new lines
-- ["Variable"] =					<Translate here>	-- Origional english text

["S_AREA_NOLORE"] =					"<HTML><BODY><BR/><P align=\"CENTER\">Об этой области ещё ничего не известно.</P></BODY></HTML>"
									-- "<HTML><BODY><BR/><P align=\"CENTER\">Not much is known about this area.</P></BODY></HTML>"
["S_CONTINENT_DRAENOR"] =			"Дренор"	-- "Draenor"
["S_CONTINENT_EK"] =				"Восточные королевства"	-- "Eastern Kingdoms"
["S_CONTINENT_KALIMDOR"] =			"Калимдор"	-- "Kalimdor"
["S_CONTINENT_NORTHREND"] =			"Нордскол"	-- "Northrend"
["S_CONTINENT_OUTLAND"] =			"Запределье"	-- "Outland"
["S_CONTINENT_PANDARIA"] =			"Пандария"	-- "Pandaria"
["S_DAILY_SUGGESTIONS"] = 			"Ежедневные предположения" -- "Daily Suggestions"
["S_ERROR_COMBATLOCKDOWN"] =		"|cFFFF0000Вы не можете открыть Lore Library, пока учавствуете в бою.|r"	-- "|cFFFF0000You can't open Lore Library while in combat.|r"
["S_LIBRARY_ADDED"] =				"Добавлено в библиотеку."	-- "Added to your library."
["S_LORE_LIBRARY"] =				"Lore Library"	-- "Lore Library"
["S_LORE_COLLECTED"] =				"Знание изучено"	-- "Lore collected"
["S_LORE_NOT_COLLECTED"] =			"Знание не изучено"	-- "Lore not collected"
["S_LOSTPAGES_INFO"] =				"Вы можете использовать утерянную страницу,\nчтобы изучить знание"	-- "You can use a lost page\nto unlock this lore."
["S_LOSTPAGE_NONE"] = 				"У вас нет утерянных страниц"	-- "You have no lost pages available."
["S_LOSTPAGE_UNLOCK_INFO"] = 		"Вы можете использовать утерянную страницу,\nчтобы изучить знание"	-- "You can use a lost page\nto unlock this lore."
["S_LOSTPAGE_USE"] = 				"Использовать утерянную страницу, чтобы изучить знание"	-- "Use a lost page to unlock this lore."
["S_LOST_PAGES"] =					"Утерянные страницы"	-- "Lost pages"
["S_MARK_WORLDMAP"] = 				"Обозначить область на карте мира" --?	-- "Mark area on the world map"
["S_MATCH_AREA"] = 					"Исследованные области" --?	-- "Discovered areas"
["S_MATCH_ZONE"] = 					"Зоны" --?	-- "Zones"
["S_MINIMAPBUTTON_INFO"] =			"Кликните, чтобы добавить в библиотеку"	-- "Click to open your library."
["S_NEW"] =							"Новое !" --?	-- "New !"
["S_OPTIONS_MAPOPTIONS"] =			"Метки на карте мира"	-- "World map pins"
["S_OPTIONS_MINIMAP"] =				"Кнопка у миникарты"	-- "Minimap button"
["S_OPTIONS_MOVEPOPUP"] =			"Переместить всплывающее сообщение"	-- "Move popup"
["S_OPTIONS_PINS_AREA"] =			"Область" --?	-- "Area"
["S_OPTIONS_PINS_LORE"] =			"Документ" --?	-- "Document"
["S_OPTIONS_PINS_TOOLTIPS"] =		"Подсказки"	-- "Tooltips"
["S_OPTIONS_PINS_UNLOCKED"] =		"Изучено"	-- "Unlocked"
["S_OPTIONS_POPUPOPTIONS"] =		"Всплывающее сообщение" --?	-- "Popups"
["S_OPTIONS_TOOLTIP"] =				"Индикатор в подсказке предмета"	-- "Tooltip indicator"
["S_OPTIONS_WORLDMAP_OVERLAY"] =	"Наложение на карту мира" --?	-- "World map overlay"
["S_PINS_OPTIONS_COLLECTED"] =		"Показывать изученные"	-- "Show collected"
["S_PINS_OPTIONS_SHOW"] =			"Показывать метки"	-- "Show pins"
["S_POI_BY_CONTINENT"] =			"Сортировать по континенту"	-- "Sort by continent"
["S_POI_COMPLETED"] =				"Завершено"	-- "Completed"
["S_POI_NOT_COMPLETED"] =			"Не завершено"	-- "Not completed"
["S_RIGHTCLICK_HIDE"] =				"Кликните правой кнопкой мыши, чтобы скрыть"	-- "Right click to hide."
["S_SOURCEINFO_CHEST"] =			"Может быть найдено в сундуке"	-- "Found in a type of chest."
["S_SOURCEINFO_CONTAINER"] =		"Может быть найдено в контейнере"	-- "Can be found in a container."
["S_SOURCEINFO_NPC"] =				"Может выпасть с"	-- "Can drop from an npc."
["S_SOURCEINFO_OBJECT"] =			"Объект в области"	-- "Object found in a zone."
["S_SOURCEINFO_QUEST"] =			"Получается в ходе выполнения задания"	-- "Obtained during a quest."
["S_SOURCEINFO_STEALTH"] =			"Может быть получено из карманов"	-- "Can pickpocket from an npc."
["S_SOURCEINFO_UNAVAILABLE"] =		"Более не доступно игрокам"	-- "Can no longer be obtained."
["S_SOURCEINFO_VENDOR"] =			"Продаётся торговцем"	-- "Sold by a vendor."
["S_SOURCETYPE_CHEST"] =			"Сундук"	-- "Chest"
["S_SOURCETYPE_CONTAINER"] =		"Контейнер"	-- "Container"
["S_SOURCETYPE_NPC"] =				"Добыча"	-- "Drop"
["S_SOURCETYPE_OBJECT"] =			"Объект"	-- "Object"
["S_SOURCETYPE_QUEST"] =			"Задание"	-- "Quest"
["S_SOURCETYPE_STEALTH"] =			"Обшаривание карманов"	-- "Pickpocket"
["S_SOURCETYPE_UNAVAILABLE"] =		"Недоступно"	-- "Unavailable"
["S_SOURCETYPE_VENDOR"] =			"Торговец"	-- "Vendor"
["S_SOURCE_TITLE"] =				"<HTML><BODY><BR/><P align=\"center\">Знание может быть получено из:</P><BR/></BODY></HTML>"
									-- "<HTML><BODY><BR/><P align=\"center\">This lore can be obtained from:</P><BR/></BODY></HTML>"
["S_SUGGESTION_COMPLETE"] =			"Предположение выполнено"	-- "Suggestion completed"
["S_SUGGESTION_EMPTY1"] =			"Вы собрали так много знаний!"	-- "You have collected so much lore!"
["S_SUGGESTION_EMPTY2"] =			"Не осталось ничего, что можно было бы предложить"	-- "There is nothing left to suggest."
["S_SUGGESTION_REMOVE"] =			"Удалить предположение, чтобы освободить место для нового"	-- "Remove this suggestion to make room for a new one."
["S_TAB_LORE"] =					"Документы" --?	-- "Documents"
["S_TAB_POI"] =						"Области" --?	-- "Areas"
["S_TITLE_AREA"] =					"Библиотека по области" --?	-- "Area Library"
["S_TITLE_DOCUMENT"] =				"Библиотека документов" --?	-- "Document Library"
["S_UNAVAILABLE_DETAIL"] =			"У этого знания больше нет доступных источников"	-- "This lore no longer has any\n available sources."
["S_UNLOCK_UNTIL_NEXT"] =			"Осталось до разблокировки:"	-- "Unlocks until next:"
["S_ZONE_COMPLETE"] =				"Локация завершена"	-- "Zone completed"

["F_LORE_CONTENT"] =				"Знание содержит:\nСлов: %d\nСтраниц: %d \nИзображений: %d"	-- "Lore content:\nWords: %d \nPages: %d \nImages: %d"
["F_LORE_UNLOCK"] = 					-- "Lore Library added: %s"
["F_LOSTPAGE_INFO"] =				"Страницы разблокируются каждые %d фрагментов знаний, которые вы изучаете, и могут быть исользованы для изучения недоступных знаний"	-- "Pages are gained with every %d pieces of lore you unlock, and can be used to unlock unavailable lore."
["F_PAGE"] =						"Страница %d"	-- "Page %d"
["F_PROGRESS"] =					"%d/%d"	-- "%d/%d"
["F_SOURCE"] =						"%s\n%s"	-- "%s\n%s"
["F_SUGGESTION_REMOVECOOLDOWN"] =	"Может быть удалено через %s."	-- "Can be removed in %s."
["F_SUGGESTION_UNTILNEW"] =			"Новое предположение через %s."	-- "New suggestion in %s."
